<?php // phpcs:disable WordPress.Files.FileName

declare( strict_types=1 );

use Lerm\OptionsFramework\Integrations\LermTheme\OptionsPageDefinition;

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

return array(
	'title'       => __( 'Account', 'lerm' ),
	'description' => __( 'Frontend login, registration, and account center settings.', 'lerm' ),
	'fields'      => array(
		array(
			'id'          => 'frontend_login',
			'type'        => 'switcher',
			'label'       => __( 'Enable frontend login', 'lerm' ),
			'description' => __( 'Turns on the theme frontend login and password reset flow.', 'lerm' ),
			'group'       => __( 'Frontend login', 'lerm' ),
			'default'     => false,
		),
		array(
			'id'               => 'frontend_login_page',
			'type'             => 'select',
			'label'            => __( 'Login page', 'lerm' ),
			'description'      => __( 'Page that renders the frontend login template.', 'lerm' ),
			'group'            => __( 'Frontend login', 'lerm' ),
			'default'          => 0,
			'choices'          => array( OptionsPageDefinition::class, 'page_choices' ),
			'cast'             => 'int',
			'dependency_field' => 'frontend_login',
			'dependency_value' => '1',
		),
		array(
			'id'               => 'menu_login_item',
			'type'             => 'switcher',
			'label'            => __( 'Add login/avatar item to navigation', 'lerm' ),
			'description'      => __( 'Shows a login or account entry in the main navigation.', 'lerm' ),
			'group'            => __( 'Frontend login', 'lerm' ),
			'default'          => false,
			'dependency_field' => 'frontend_login',
			'dependency_value' => '1',
		),
		array(
			'id'               => 'login_redirect_url',
			'type'             => 'switcher',
			'label'            => __( 'Redirect to homepage after login', 'lerm' ),
			'description'      => __( 'If disabled, successful login goes to the configured account page.', 'lerm' ),
			'group'            => __( 'Frontend login', 'lerm' ),
			'default'          => false,
			'dependency_field' => 'frontend_login',
			'dependency_value' => '1',
		),
		array(
			'id'               => 'logout_redirect_url',
			'type'             => 'switcher',
			'label'            => __( 'Redirect to homepage after logout', 'lerm' ),
			'description'      => __( 'If disabled, logout returns visitors to the frontend login page.', 'lerm' ),
			'group'            => __( 'Frontend login', 'lerm' ),
			'default'          => false,
			'dependency_field' => 'frontend_login',
			'dependency_value' => '1',
		),
		array(
			'id'               => 'frontend_regist',
			'type'             => 'switcher',
			'label'            => __( 'Allow frontend registration', 'lerm' ),
			'description'      => __( 'Shows registration in the frontend auth flow.', 'lerm' ),
			'group'            => __( 'Registration', 'lerm' ),
			'default'          => false,
			'dependency_field' => 'frontend_login',
			'dependency_value' => '1',
		),
		array(
			'id'               => 'users_can_register',
			'type'             => 'switcher',
			'label'            => __( 'Open registration to everyone', 'lerm' ),
			'description'      => __( 'Maps to the WordPress "Anyone can register" behaviour through the theme auth layer.', 'lerm' ),
			'group'            => __( 'Registration', 'lerm' ),
			'default'          => false,
			'dependency_field' => 'frontend_regist',
			'dependency_value' => '1',
		),
		array(
			'id'               => 'default_role',
			'type'             => 'select',
			'label'            => __( 'Default user role', 'lerm' ),
			'description'      => __( 'Role assigned to newly registered users.', 'lerm' ),
			'group'            => __( 'Registration', 'lerm' ),
			'default'          => get_option( 'default_role', 'subscriber' ),
			'choices'          => array( OptionsPageDefinition::class, 'role_choices' ),
			'dependency_field' => 'frontend_regist',
			'dependency_value' => '1',
		),
		array(
			'id'               => 'default_login_page',
			'type'             => 'switcher',
			'label'            => __( 'Disable wp-login.php', 'lerm' ),
			'description'      => __( 'Redirect most direct visits to wp-login.php into the frontend auth page.', 'lerm' ),
			'group'            => __( 'Registration', 'lerm' ),
			'default'          => false,
			'dependency_field' => 'frontend_regist',
			'dependency_value' => '1',
		),
		array(
			'id'               => 'front_user_center',
			'type'             => 'switcher',
			'label'            => __( 'Enable frontend account center', 'lerm' ),
			'description'      => __( 'Turns on the frontend user center experience.', 'lerm' ),
			'group'            => __( 'Account center', 'lerm' ),
			'default'          => false,
			'dependency_field' => 'frontend_login',
			'dependency_value' => '1',
		),
		array(
			'id'               => 'frontend_user_center_page',
			'type'             => 'select',
			'label'            => __( 'Account center page', 'lerm' ),
			'description'      => __( 'Page that renders the frontend account center template.', 'lerm' ),
			'group'            => __( 'Account center', 'lerm' ),
			'default'          => 0,
			'choices'          => array( OptionsPageDefinition::class, 'page_choices' ),
			'cast'             => 'int',
			'dependency_field' => 'front_user_center',
			'dependency_value' => '1',
		),
		array(
			'id'               => 'frontend_profile',
			'type'             => 'switcher',
			'label'            => __( 'Enable profile editing', 'lerm' ),
			'description'      => __( 'Shows frontend profile editing inside the account center.', 'lerm' ),
			'group'            => __( 'Account center', 'lerm' ),
			'default'          => false,
			'dependency_field' => 'frontend_regist',
			'dependency_value' => '1',
		),
		array(
			'id'               => 'favorite_post',
			'type'             => 'switcher',
			'label'            => __( 'Enable post favorites', 'lerm' ),
			'description'      => __( 'Reserved switch for favorites features in the account center.', 'lerm' ),
			'group'            => __( 'Account center', 'lerm' ),
			'default'          => false,
			'dependency_field' => 'frontend_regist',
			'dependency_value' => '1',
		),
		array(
			'id'               => 'my_posts',
			'type'             => 'switcher',
			'label'            => __( 'Enable "My Posts" section', 'lerm' ),
			'description'      => __( 'Reserved switch for author-owned content features in the account center.', 'lerm' ),
			'group'            => __( 'Account center', 'lerm' ),
			'default'          => false,
			'dependency_field' => 'frontend_regist',
			'dependency_value' => '1',
		),
	),
);
