<?php // phpcs:disable WordPress.Files.FileName

declare( strict_types=1 );

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

return array(
	'title'       => __( 'Appearance+', 'lerm' ),
	'description' => __( 'Advanced styling, dark mode, and utility UI elements.', 'lerm' ),
	'fields'      => array(
		array(
			'id'          => 'custom_css',
			'type'        => 'code_editor',
			'label'       => __( 'Custom CSS', 'lerm' ),
			'description' => __( 'CSS entered here is output in a style tag in the page head.', 'lerm' ),
			'group'       => __( 'Custom CSS', 'lerm' ),
			'default'     => '',
			'rows'        => 12,
		),
		array(
			'id'          => 'dark_mode_enable',
			'type'        => 'switcher',
			'label'       => __( 'Enable dark mode support', 'lerm' ),
			'description' => __( 'Adds a visitor-facing toggle between light and dark themes.', 'lerm' ),
			'group'       => __( 'Dark mode', 'lerm' ),
			'default'     => false,
		),
		array(
			'id'               => 'dark_mode_default',
			'type'             => 'button_set',
			'label'            => __( 'Default color scheme', 'lerm' ),
			'description'      => __( 'Choose whether visitors start in light, dark, or system-following mode.', 'lerm' ),
			'group'            => __( 'Dark mode', 'lerm' ),
			'default'          => 'system',
			'choices'          => array(
				'light'  => __( 'Light', 'lerm' ),
				'dark'   => __( 'Dark', 'lerm' ),
				'system' => __( 'Follow system', 'lerm' ),
			),
			'dependency_field' => 'dark_mode_enable',
			'dependency_value' => '1',
		),
		array(
			'id'               => 'dark_mode_toggle_position',
			'type'             => 'button_set',
			'label'            => __( 'Toggle button position', 'lerm' ),
			'description'      => __( 'Choose whether the dark-mode toggle lives in the navbar or as a floating sidebar button.', 'lerm' ),
			'group'            => __( 'Dark mode', 'lerm' ),
			'default'          => 'navbar',
			'choices'          => array(
				'navbar'  => __( 'In navbar', 'lerm' ),
				'sidebar' => __( 'Floating button', 'lerm' ),
			),
			'dependency_field' => 'dark_mode_enable',
			'dependency_value' => '1',
		),
		array(
			'id'               => 'dark_bg_body',
			'type'             => 'color',
			'label'            => __( 'Body background', 'lerm' ),
			'description'      => __( 'Page-level background color in dark mode.', 'lerm' ),
			'group'            => __( 'Dark palette', 'lerm' ),
			'default'          => '#1a1b1e',
			'dependency_field' => 'dark_mode_enable',
			'dependency_value' => '1',
		),
		array(
			'id'               => 'dark_bg_card',
			'type'             => 'color',
			'label'            => __( 'Card background', 'lerm' ),
			'description'      => __( 'Background color for cards and content surfaces in dark mode.', 'lerm' ),
			'group'            => __( 'Dark palette', 'lerm' ),
			'default'          => '#25262b',
			'dependency_field' => 'dark_mode_enable',
			'dependency_value' => '1',
		),
		array(
			'id'               => 'dark_bg_header',
			'type'             => 'color',
			'label'            => __( 'Header background', 'lerm' ),
			'group'            => __( 'Dark palette', 'lerm' ),
			'default'          => '#1f2023',
			'dependency_field' => 'dark_mode_enable',
			'dependency_value' => '1',
		),
		array(
			'id'               => 'dark_text',
			'type'             => 'color',
			'label'            => __( 'Body text color', 'lerm' ),
			'group'            => __( 'Dark palette', 'lerm' ),
			'default'          => '#c1c2c5',
			'dependency_field' => 'dark_mode_enable',
			'dependency_value' => '1',
		),
		array(
			'id'               => 'dark_text_muted',
			'type'             => 'color',
			'label'            => __( 'Muted text color', 'lerm' ),
			'description'      => __( 'Used for secondary metadata, captions, and placeholders in dark mode.', 'lerm' ),
			'group'            => __( 'Dark palette', 'lerm' ),
			'default'          => '#909296',
			'dependency_field' => 'dark_mode_enable',
			'dependency_value' => '1',
		),
		array(
			'id'               => 'dark_border',
			'type'             => 'color',
			'label'            => __( 'Border color', 'lerm' ),
			'group'            => __( 'Dark palette', 'lerm' ),
			'default'          => '#373a40',
			'dependency_field' => 'dark_mode_enable',
			'dependency_value' => '1',
		),
		array(
			'id'               => 'dark_footer_bg',
			'type'             => 'color',
			'label'            => __( 'Footer widgets background', 'lerm' ),
			'group'            => __( 'Dark palette', 'lerm' ),
			'default'          => '#141517',
			'dependency_field' => 'dark_mode_enable',
			'dependency_value' => '1',
		),
		array(
			'id'               => 'dark_bar_bg',
			'type'             => 'color',
			'label'            => __( 'Footer bar background', 'lerm' ),
			'group'            => __( 'Dark palette', 'lerm' ),
			'default'          => '#101113',
			'dependency_field' => 'dark_mode_enable',
			'dependency_value' => '1',
		),
		array(
			'id'          => 'reading_progress',
			'type'        => 'switcher',
			'label'       => __( 'Show reading progress bar', 'lerm' ),
			'description' => __( 'Displays a slim reading-progress bar at the very top of single posts.', 'lerm' ),
			'group'       => __( 'Reader UI', 'lerm' ),
			'default'     => false,
		),
		array(
			'id'               => 'reading_progress_color',
			'type'             => 'color',
			'label'            => __( 'Progress bar color', 'lerm' ),
			'group'            => __( 'Reader UI', 'lerm' ),
			'default'          => '#0084ba',
			'dependency_field' => 'reading_progress',
			'dependency_value' => '1',
		),
		array(
			'id'               => 'reading_progress_height',
			'type'             => 'number',
			'label'            => __( 'Progress bar height (px)', 'lerm' ),
			'group'            => __( 'Reader UI', 'lerm' ),
			'default'          => 3,
			'min'              => 1,
			'max'              => 10,
			'step'             => 1,
			'dependency_field' => 'reading_progress',
			'dependency_value' => '1',
		),
		array(
			'id'          => 'back_to_top',
			'type'        => 'switcher',
			'label'       => __( 'Show back-to-top button', 'lerm' ),
			'group'       => __( 'Utility buttons', 'lerm' ),
			'default'     => true,
		),
		array(
			'id'               => 'back_to_top_threshold',
			'type'             => 'number',
			'label'            => __( 'Back-to-top threshold (px)', 'lerm' ),
			'description'      => __( 'The button appears after the visitor scrolls this many pixels.', 'lerm' ),
			'group'            => __( 'Utility buttons', 'lerm' ),
			'default'          => 400,
			'min'              => 100,
			'max'              => 2000,
			'step'             => 50,
			'dependency_field' => 'back_to_top',
			'dependency_value' => '1',
		),
		array(
			'id'          => 'qq_chat_enable',
			'type'        => 'switcher',
			'label'       => __( 'Show QQ live chat button', 'lerm' ),
			'group'       => __( 'Utility buttons', 'lerm' ),
			'default'     => false,
		),
		array(
			'id'               => 'qq_chat_number',
			'type'             => 'text',
			'label'            => __( 'QQ number', 'lerm' ),
			'description'      => __( 'Opens a QQ chat window when the floating button is clicked.', 'lerm' ),
			'group'            => __( 'Utility buttons', 'lerm' ),
			'default'          => '',
			'placeholder'      => '825641026',
			'dependency_field' => 'qq_chat_enable',
			'dependency_value' => '1',
		),
	),
);
