<?php // phpcs:disable WordPress.Files.FileName

declare( strict_types=1 );

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

return array(
	'title'       => __( 'Comments', 'lerm' ),
	'description' => __( 'Global comment behaviour, form rules, and avatar presentation.', 'lerm' ),
	'fields'      => array(
		array(
			'id'          => 'comments_enable',
			'type'        => 'switcher',
			'label'       => __( 'Enable comments globally', 'lerm' ),
			'description' => __( 'When disabled, comments are closed everywhere regardless of per-post settings.', 'lerm' ),
			'group'       => __( 'Comment behaviour', 'lerm' ),
			'default'     => true,
		),
		array(
			'id'               => 'comments_require_login',
			'type'             => 'switcher',
			'label'            => __( 'Require login to comment', 'lerm' ),
			'description'      => __( 'Visitors must sign in before they can submit comments.', 'lerm' ),
			'group'            => __( 'Comment behaviour', 'lerm' ),
			'default'          => false,
			'dependency_field' => 'comments_enable',
			'dependency_value' => '1',
		),
		array(
			'id'               => 'comment_moderation',
			'type'             => 'switcher',
			'label'            => __( 'Hold comments for moderation', 'lerm' ),
			'description'      => __( 'All new comments must be approved before showing publicly.', 'lerm' ),
			'group'            => __( 'Comment behaviour', 'lerm' ),
			'default'          => false,
			'dependency_field' => 'comments_enable',
			'dependency_value' => '1',
		),
		array(
			'id'               => 'comments_per_page',
			'type'             => 'number',
			'label'            => __( 'Comments per page', 'lerm' ),
			'description'      => __( 'How many comments to display before pagination kicks in.', 'lerm' ),
			'group'            => __( 'Comment behaviour', 'lerm' ),
			'default'          => 20,
			'min'              => 5,
			'max'              => 100,
			'step'             => 5,
			'dependency_field' => 'comments_enable',
			'dependency_value' => '1',
		),
		array(
			'id'               => 'comment_nesting_depth',
			'type'             => 'number',
			'label'            => __( 'Maximum nesting depth', 'lerm' ),
			'description'      => __( 'How many threaded reply levels are allowed.', 'lerm' ),
			'group'            => __( 'Comment behaviour', 'lerm' ),
			'default'          => 3,
			'min'              => 1,
			'max'              => 10,
			'step'             => 1,
			'dependency_field' => 'comments_enable',
			'dependency_value' => '1',
		),
		array(
			'id'               => 'comment_form_fields',
			'type'             => 'checkbox_list',
			'label'            => __( 'Required form fields', 'lerm' ),
			'description'      => __( 'Choose which identity fields are required in the comment form.', 'lerm' ),
			'group'            => __( 'Comment form', 'lerm' ),
			'default'          => array( 'name', 'email' ),
			'choices'          => array(
				'name'    => __( 'Name', 'lerm' ),
				'email'   => __( 'Email', 'lerm' ),
				'website' => __( 'Website', 'lerm' ),
			),
			'dependency_field' => 'comments_enable',
			'dependency_value' => '1',
		),
		array(
			'id'               => 'comment_placeholder',
			'type'             => 'text',
			'label'            => __( 'Comment textarea placeholder', 'lerm' ),
			'description'      => __( 'Prompt shown in the comment textarea before the visitor types.', 'lerm' ),
			'group'            => __( 'Comment form', 'lerm' ),
			'default'          => '',
			'placeholder'      => __( 'Leave a comment...', 'lerm' ),
			'dependency_field' => 'comments_enable',
			'dependency_value' => '1',
		),
		array(
			'id'               => 'comment_min_length',
			'type'             => 'number',
			'label'            => __( 'Minimum comment length', 'lerm' ),
			'description'      => __( 'Set to 0 to disable the minimum length check.', 'lerm' ),
			'group'            => __( 'Comment form', 'lerm' ),
			'default'          => 10,
			'min'              => 0,
			'max'              => 500,
			'step'             => 1,
			'dependency_field' => 'comments_enable',
			'dependency_value' => '1',
		),
		array(
			'id'               => 'comment_max_length',
			'type'             => 'number',
			'label'            => __( 'Maximum comment length', 'lerm' ),
			'description'      => __( 'Set to 0 to remove the maximum length limit.', 'lerm' ),
			'group'            => __( 'Comment form', 'lerm' ),
			'default'          => 2000,
			'min'              => 0,
			'max'              => 10000,
			'step'             => 100,
			'dependency_field' => 'comments_enable',
			'dependency_value' => '1',
		),
		array(
			'id'          => 'comment_avatar_size',
			'type'        => 'number',
			'label'       => __( 'Comment avatar size', 'lerm' ),
			'description' => __( 'Avatar size in pixels for the comment list.', 'lerm' ),
			'group'       => __( 'Avatar', 'lerm' ),
			'default'     => 48,
			'min'         => 24,
			'max'         => 128,
			'step'        => 4,
		),
		array(
			'id'          => 'comment_show_cravatar_tip',
			'type'        => 'switcher',
			'label'       => __( 'Show Cravatar tip', 'lerm' ),
			'description' => __( 'Display a hint encouraging users without an avatar to set one on Cravatar.cn.', 'lerm' ),
			'group'       => __( 'Avatar', 'lerm' ),
			'default'     => true,
		),
	),
);
