<?php // phpcs:disable WordPress.Files.FileName

declare( strict_types=1 );

use Lerm\OptionsFramework\Integrations\LermTheme\OptionsPageDefinition;

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

return array(
	'title'       => __( 'Community', 'lerm' ),
	'description' => __( 'Share-platform controls, WeChat QR data, and donation media moved out of the legacy CSF social tab.', 'lerm' ),
	'groups'      => array(
		array(
			'id'    => 'social',
			'label' => __( 'Social', 'lerm' ),
		),
		array(
			'id'    => 'profile',
			'label' => __( 'Profiles', 'lerm' ),
		),
		array(
			'id'    => 'ad',
			'label' => __( 'Advertisement', 'lerm' ),
		),
	),
	'fields'      => array(
		array(
			'id'          => 'qrcode_image',
			'group_id'    => 'social',
			'type'        => 'fieldset',
			'label'       => __( 'WeChat QR code', 'lerm' ),
			'description' => __( 'Optional image URL shown when visitors hover over the WeChat social link.', 'lerm' ),
			'group'       => __( 'Social assets', 'lerm' ),
			'default'     => array(
				'background-image' => '',
			),
			'fields'      => array(
				array(
					'id'          => 'background-image',
					'type'        => 'url',
					'label'       => __( 'Image URL', 'lerm' ),
					'default'     => '',
					'placeholder' => 'https://example.com/wechat-qr.png',
				),
			),
		),
		array(
			'id'          => 'donate_qrcode',
			'type'        => 'media',
			'label'       => __( 'Donation QR code', 'lerm' ),
			'description' => __( 'Payment QR code displayed by donation-related UI blocks.', 'lerm' ),
			'group'       => __( 'Social assets', 'lerm' ),
			'default'     => array(),
		),
		array(
			'id'          => 'social_share',
			'type'        => 'checkbox_list',
			'label'       => __( 'Share buttons', 'lerm' ),
			'description' => __( 'Select which social platforms should appear in share UI on single posts.', 'lerm' ),
			'group'       => __( 'Share buttons', 'lerm' ),
			'default'     => array(),
			'choices'     => array( OptionsPageDefinition::class, 'social_share_choices' ),
		),
		array(
			'id'          => 'social_weibo',
			'group_id'    => 'profile',
			'type'        => 'url',
			'label'       => 'Weibo',
			'group'       => __( 'Chinese platforms', 'lerm' ),
			'default'     => '',
			'placeholder' => 'https://weibo.com/yourname',
		),
		array(
			'id'          => 'social_wechat',
			'group_id'    => 'profile',
			'type'        => 'text',
			'label'       => 'WeChat',
			'group'       => __( 'Chinese platforms', 'lerm' ),
			'default'     => '',
			'placeholder' => 'your-public-account-id',
		),
		array(
			'id'          => 'social_qq',
			'group_id'    => 'profile',
			'type'        => 'text',
			'label'       => 'QQ',
			'group'       => __( 'Chinese platforms', 'lerm' ),
			'default'     => '',
			'placeholder' => 'https://wpa.qq.com/msgrd?v=3&uin=123456',
		),
		array(
			'id'          => 'social_bilibili',
			'group_id'    => 'profile',
			'type'        => 'url',
			'label'       => 'Bilibili',
			'group'       => __( 'Chinese platforms', 'lerm' ),
			'default'     => '',
			'placeholder' => 'https://space.bilibili.com/youruid',
		),
		array(
			'id'          => 'social_zhihu',
			'group_id'    => 'profile',

			'type'        => 'url',
			'label'       => 'Zhihu',
			'group'       => __( 'Chinese platforms', 'lerm' ),
			'default'     => '',
			'placeholder' => 'https://www.zhihu.com/people/yourname',
		),
		array(
			'id'          => 'social_douban',
			'group_id'    => 'profile',
			'type'        => 'url',
			'label'       => 'Douban',
			'group'       => __( 'Chinese platforms', 'lerm' ),
			'default'     => '',
			'placeholder' => 'https://www.douban.com/people/yourname',
		),
		array(
			'id'          => 'social_github',
			'group_id'    => 'profile',
			'type'        => 'url',
			'label'       => 'GitHub',
			'group'       => __( 'International platforms', 'lerm' ),
			'default'     => '',
			'placeholder' => 'https://github.com/yourname',
		),
		array(
			'id'          => 'social_twitter',
			'group_id'    => 'profile',
			'type'        => 'url',
			'label'       => 'X / Twitter',
			'group'       => __( 'International platforms', 'lerm' ),
			'default'     => '',
			'placeholder' => 'https://x.com/yourhandle',
		),
		array(
			'id'          => 'social_linkedin',
			'group_id'    => 'profile',
			'type'        => 'url',
			'label'       => 'LinkedIn',
			'group'       => __( 'International platforms', 'lerm' ),
			'default'     => '',
			'placeholder' => 'https://linkedin.com/in/yourname',
		),
		array(
			'id'          => 'social_instagram',
			'group_id'    => 'profile',
			'type'        => 'url',
			'label'       => 'Instagram',
			'group'       => __( 'International platforms', 'lerm' ),
			'default'     => '',
			'placeholder' => 'https://instagram.com/yourname',
		),
		array(
			'id'          => 'social_youtube',
			'group_id'    => 'profile',
			'type'        => 'url',
			'label'       => 'YouTube',
			'group'       => __( 'International platforms', 'lerm' ),
			'default'     => '',
			'placeholder' => 'https://youtube.com/@yourchannel',
		),
		array(
			'id'          => 'social_email',
			'group_id'    => 'profile',
			'type'        => 'text',
			'label'       => __( 'Email', 'lerm' ),
			'group'       => __( 'International platforms', 'lerm' ),
			'default'     => '',
			'placeholder' => 'hello@example.com',
		),
		array(
			'id'       => 'social_rss',
			'group_id' => 'profile',
			'type'     => 'switcher',
			'label'    => __( 'Show RSS feed link', 'lerm' ),
			'group'    => __( 'Display settings', 'lerm' ),
			'default'  => true,
		),
		array(
			'id'       => 'social_profiles_position',
			'group_id' => 'profile',
			'type'     => 'checkbox_list',
			'label'    => __( 'Show social links in', 'lerm' ),
			'group'    => __( 'Display settings', 'lerm' ),
			'default'  => array( 'footer', 'author_bio' ),
			'choices'  => array(
				'header'     => __( 'Header', 'lerm' ),
				'footer'     => __( 'Footer', 'lerm' ),
				'author_bio' => __( 'Author bio box', 'lerm' ),
			),
		),
		array(
			'id'      => 'social_open_new_tab',
			'type'    => 'switcher',
			'label'   => __( 'Open links in a new tab', 'lerm' ),
			'group'   => __( 'Display settings', 'lerm' ),
			'default' => true,
		),
		array(
			'id'          => 'ad_switcher',
			'group_id'    => 'ad',
			'type'        => 'switcher',
			'label'       => __( 'Show advertisements', 'lerm' ),
			'description' => __( 'Reserved global switch for theme-owned ad slots.', 'lerm' ),
			'group'       => __( 'Homepage advertisement', 'lerm' ),
			'default'     => false,
		),
		array(
			'id'               => 'ad1',
			'group_id'         => 'ad',
			'type'             => 'wp_editor',
			'label'            => __( 'Homepage ad code', 'lerm' ),
			'description'      => __( 'Paste ad embed code for the homepage slot.', 'lerm' ),
			'group'            => __( 'Homepage advertisement', 'lerm' ),
			'default'          => '',
			'dependency_field' => 'ad_switcher',
			'dependency_value' => '1',
			'editor_args'      => array(
				'textarea_rows' => 6,
				'media_buttons' => false,
				'quicktags'     => false,
				'tinymce'       => false,
			),
		),

	),
);
