<?php // phpcs:disable WordPress.Files.FileName

declare( strict_types=1 );

use Lerm\OptionsFramework\Integrations\LermTheme\OptionsPageDefinition;

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

return array(
	'title'       => __( 'Content', 'lerm' ),
	'description' => __( 'Static-page content rules that used to live in the CSF Page tab.', 'lerm' ),
	'groups'      => array(
		array(
			'id'    => 'search',
			'label' => __( 'Search behaviour', 'lerm' ),
		),
		array(
			'id'    => 'carousel',
			'label' => __( 'Carousel', 'lerm' ),
		),
		array(
			'id'    => 'content_404',
			'label' => __( '404 page', 'lerm' ),
		),
		array(
			'id'    => 'posts',
			'label' => __( 'Posts', 'lerm' ),
		),
		array(
			'id'    => 'sidebars',
			'label' => __( 'Sidebars', 'lerm' ),
		),
	),
	'fields'      => array(
		array(
			'id'          => 'search_filter',
			'group_id'    => 'search',
			'type'        => 'switcher',
			'label'       => __( 'Exclude pages from search results', 'lerm' ),
			'description' => __( 'When enabled, WordPress search only returns posts instead of mixing in static pages.', 'lerm' ),
			'group'       => __( 'Search behaviour', 'lerm' ),
			'default'     => true,
		),
		array(
			'id'          => 'search_results_per_page',
			'group_id'    => 'search',
			'type'        => 'number',
			'label'       => __( 'Instant search results count', 'lerm' ),
			'description' => __( 'Maximum number of items shown in the instant search dropdown.', 'lerm' ),
			'group'       => __( 'Instant search', 'lerm' ),
			'default'     => 5,
			'min'         => 1,
			'max'         => 20,
			'step'        => 1,
		),
		array(
			'id'          => 'search_placeholder',
			'group_id'    => 'search',
			'type'        => 'text',
			'label'       => __( 'Search box placeholder', 'lerm' ),
			'description' => __( 'Placeholder shown in the search form and instant search field.', 'lerm' ),
			'group'       => __( 'Instant search', 'lerm' ),
			'default'     => '',
			'placeholder' => __( 'Search...', 'lerm' ),
		),
		array(
			'id'          => 'slide_enable',
			'group_id'    => 'carousel',
			'type'        => 'switcher',
			'label'       => __( 'Enable homepage slider', 'lerm' ),
			'description' => __( 'Shows the carousel block on the homepage when slides exist.', 'lerm' ),
			'group'       => __( 'Carousel', 'lerm' ),
			'default'     => false,
		),
		array(
			'id'               => 'slide_position',
			'group_id'         => 'carousel',
			'type'             => 'button_set',
			'label'            => __( 'Slider position', 'lerm' ),
			'description'      => __( 'Controls how wide the homepage slider should be rendered.', 'lerm' ),
			'group'            => __( 'Carousel', 'lerm' ),
			'default'          => 'under_navbar',
			'choices'          => array(
				'under_navbar'  => __( 'Under navbar', 'lerm' ),
				'under_primary' => __( 'Content width', 'lerm' ),
				'full_width'    => __( 'Full width', 'lerm' ),
			),
			'dependency_field' => 'slide_enable',
			'dependency_value' => '1',
		),
		array(
			'id'               => 'slide_indicators',
			'group_id'         => 'carousel',
			'type'             => 'switcher',
			'label'            => __( 'Show indicators', 'lerm' ),
			'description'      => __( 'Displays the small dots beneath the carousel.', 'lerm' ),
			'group'            => __( 'Carousel', 'lerm' ),
			'default'          => false,
			'dependency_field' => 'slide_enable',
			'dependency_value' => '1',
		),
		array(
			'id'               => 'slide_control',
			'group_id'         => 'carousel',
			'type'             => 'switcher',
			'label'            => __( 'Show previous / next controls', 'lerm' ),
			'group'            => __( 'Carousel', 'lerm' ),
			'default'          => false,
			'dependency_field' => 'slide_enable',
			'dependency_value' => '1',
		),
		array(
			'id'               => 'slide_images',
			'group_id'         => 'carousel',
			'type'             => 'group',
			'label'            => __( 'Slides', 'lerm' ),
			'description'      => __( 'Each slide can include an image, title, optional link, and caption text.', 'lerm' ),
			'group'            => __( 'Slides', 'lerm' ),
			'default'          => array(),
			'button_text'      => __( 'Add slide', 'lerm' ),
			'dependency_field' => 'slide_enable',
			'dependency_value' => '1',
			'fields'           => array(
				array(
					'id'          => 'image',
					'type'        => 'media',
					'label'       => __( 'Slide image', 'lerm' ),
					'description' => __( 'Main slide image displayed in the carousel.', 'lerm' ),
					'default'     => array(),
				),
				array(
					'id'          => 'title',
					'type'        => 'text',
					'label'       => __( 'Caption title', 'lerm' ),
					'default'     => '',
					'placeholder' => __( 'Hero title', 'lerm' ),
				),
				array(
					'id'          => 'url',
					'type'        => 'url',
					'label'       => __( 'Link URL', 'lerm' ),
					'default'     => '',
					'placeholder' => 'https://example.com/article',
				),
				array(
					'id'          => 'description',
					'type'        => 'textarea',
					'label'       => __( 'Caption text', 'lerm' ),
					'default'     => '',
					'rows'        => 3,
					'placeholder' => __( 'Short supporting text shown over the slide.', 'lerm' ),
				),
			),
		),
		array(
			'id'       => '404_title',
			'group_id' => 'content_404',
			'type'     => 'text',
			'label'    => __( 'Page title', 'lerm' ),
			'group'    => __( '404 page', 'lerm' ),
			'default'  => __( '404 Not Found', 'lerm' ),
		),
		array(
			'id'       => '404_message',
			'group_id' => 'content_404',
			'type'     => 'textarea',
			'label'    => __( 'Error message', 'lerm' ),
			'group'    => __( '404 page', 'lerm' ),
			'default'  => __( 'Sorry, the page you are looking for could not be found.', 'lerm' ),
			'rows'     => 3,
		),
		array(
			'id'       => '404_button_text',
			'group_id' => 'content_404',
			'type'     => 'text',
			'label'    => __( 'Button label', 'lerm' ),
			'group'    => __( '404 page', 'lerm' ),
			'default'  => __( 'Back to home', 'lerm' ),
		),
		array(
			'id'          => '404_button_url',
			'group_id'    => 'content_404',
			'type'        => 'url',
			'label'       => __( 'Button URL', 'lerm' ),
			'description' => __( 'Leave empty to send visitors back to the homepage.', 'lerm' ),
			'group'       => __( '404 page', 'lerm' ),
			'default'     => '',
			'placeholder' => home_url( '/' ),
		),
		array(
			'id'          => '404_image',
			'group_id'    => 'content_404',
			'type'        => 'media',
			'label'       => __( 'Custom illustration', 'lerm' ),
			'description' => __( 'Optional image used instead of the default 404 illustration.', 'lerm' ),
			'group'       => __( '404 page', 'lerm' ),
			'default'     => array(),
		),
		array(
			'id'       => '404_show_search',
			'group_id' => 'content_404',
			'type'     => 'switcher',
			'label'    => __( 'Show search box', 'lerm' ),
			'group'    => __( '404 page', 'lerm' ),
			'default'  => true,
		),

		// Other content-related settings such as sidebars used to be in the CSF Page tab but have been moved here since they also affect posts and other content types.
		array(
			'id'          => 'summary_or_full',
			'group_id'    => 'posts',
			'type'        => 'radio',
			'label'       => __( 'Archive post display mode', 'lerm' ),
			'description' => __( 'Choose whether archive pages render full post bodies or excerpts.', 'lerm' ),
			'group'       => __( 'Archive cards', 'lerm' ),
			'default'     => 'content_summary',
			'choices'     => array(
				'content_full'    => __( 'Full content', 'lerm' ),
				'content_summary' => __( 'Excerpt only', 'lerm' ),
			),
		),
		array(
			'id'          => 'excerpt_length',
			'group_id'    => 'posts',
			'type'        => 'number',
			'label'       => __( 'Excerpt length (words)', 'lerm' ),
			'description' => __( 'Number of words shown in automatically generated excerpts.', 'lerm' ),
			'group'       => __( 'Archive cards', 'lerm' ),
			'default'     => 95,
			'min'         => 0,
			'max'         => 300,
			'step'        => 5,
		),
		array(
			'id'          => 'show_thumbnail',
			'group_id'    => 'posts',
			'type'        => 'switcher',
			'label'       => __( 'Show archive thumbnails', 'lerm' ),
			'description' => __( 'Displays featured or fallback thumbnails on archive cards.', 'lerm' ),
			'group'       => __( 'Archive cards', 'lerm' ),
			'default'     => true,
		),
		array(
			'id'               => 'thumbnail_gallery',
			'group_id'         => 'posts',
			'type'             => 'gallery',
			'label'            => __( 'Fallback thumbnail pool', 'lerm' ),
			'description'      => __( 'Images used when a post does not have a featured image.', 'lerm' ),
			'group'            => __( 'Archive cards', 'lerm' ),
			'default'          => array(),
			'dependency_field' => 'show_thumbnail',
			'dependency_value' => '1',
		),
		array(
			'id'          => 'cat_exclude',
			'group_id'    => 'posts',
			'type'        => 'checkbox_list',
			'label'       => __( 'Exclude categories', 'lerm' ),
			'description' => __( 'Posts in these categories will not appear on the main blog archive.', 'lerm' ),
			'group'       => __( 'Archive cards', 'lerm' ),
			'default'     => array(),
			'choices'     => array( OptionsPageDefinition::class, 'category_choices' ),
		),
		array(
			'id'          => 'load_more',
			'group_id'    => 'posts',
			'type'        => 'switcher',
			'label'       => __( 'Ajax "Load more" pagination', 'lerm' ),
			'description' => __( 'Replaces standard archive pagination with a load-more button.', 'lerm' ),
			'group'       => __( 'Archive cards', 'lerm' ),
			'default'     => false,
		),
		array(
			'id'       => 'loading_animate',
			'group_id' => 'posts',
			'type'     => 'switcher',
			'label'    => __( 'Archive card entrance animation', 'lerm' ),
			'group'    => __( 'Archive cards', 'lerm' ),
			'default'  => false,
		),
		array(
			'id'          => 'summary_meta',
			'group_id'    => 'posts',
			'type'        => 'sorter',
			'label'       => __( 'Archive meta items', 'lerm' ),
			'description' => __( 'Drag to set order, then tick the items that should appear below archive cards.', 'lerm' ),
			'group'       => __( 'Archive cards', 'lerm' ),
			'default'     => OptionsPageDefinition::summary_meta_default(),
			'choices'     => array( OptionsPageDefinition::class, 'post_meta_choices' ),
		),
		array(
			'id'       => 'post_navigation',
			'group_id' => 'posts',
			'type'     => 'switcher',
			'label'    => __( 'Previous / next post navigation', 'lerm' ),
			'group'    => __( 'Single post', 'lerm' ),
			'default'  => true,
		),
		array(
			'id'       => 'disable_pingback',
			'group_id' => 'posts',
			'type'     => 'switcher',
			'label'    => __( 'Disable pingbacks', 'lerm' ),
			'group'    => __( 'Single post', 'lerm' ),
			'default'  => false,
		),
		array(
			'id'          => 'enable_code_highlight',
			'group_id'    => 'posts',
			'type'        => 'switcher',
			'label'       => __( 'Syntax highlighting', 'lerm' ),
			'description' => __( 'Enable Prism.js highlighting for code blocks inside posts.', 'lerm' ),
			'group'       => __( 'Single post', 'lerm' ),
			'default'     => false,
		),
		array(
			'id'          => 'author_bio',
			'group_id'    => 'posts',
			'type'        => 'switcher',
			'label'       => __( 'Author bio box', 'lerm' ),
			'description' => __( 'Show the author biography card below single posts.', 'lerm' ),
			'group'       => __( 'Single post', 'lerm' ),
			'default'     => false,
		),
		array(
			'id'       => 'related_posts',
			'group_id' => 'posts',
			'type'     => 'switcher',
			'label'    => __( 'Show related posts', 'lerm' ),
			'group'    => __( 'Single post', 'lerm' ),
			'default'  => false,
		),
		array(
			'id'               => 'related_number',
			'group_id'         => 'posts',
			'type'             => 'number',
			'label'            => __( 'Related posts count', 'lerm' ),
			'group'            => __( 'Single post', 'lerm' ),
			'default'          => 5,
			'min'              => 1,
			'max'              => 12,
			'step'             => 1,
			'dependency_field' => 'related_posts',
			'dependency_value' => '1',
		),
		array(
			'id'          => 'single_top',
			'group_id'    => 'posts',
			'type'        => 'sorter',
			'label'       => __( 'Header meta items', 'lerm' ),
			'description' => __( 'Controls the post meta shown above the article body.', 'lerm' ),
			'group'       => __( 'Single post meta', 'lerm' ),
			'default'     => OptionsPageDefinition::single_top_default(),
			'choices'     => array( OptionsPageDefinition::class, 'post_meta_choices' ),
		),
		array(
			'id'          => 'single_bottom',
			'group_id'    => 'posts',
			'type'        => 'sorter',
			'label'       => __( 'Footer meta items', 'lerm' ),
			'description' => __( 'Controls the post meta shown below the article body.', 'lerm' ),
			'group'       => __( 'Single post meta', 'lerm' ),
			'default'     => OptionsPageDefinition::single_bottom_default(),
			'choices'     => array( OptionsPageDefinition::class, 'post_meta_choices' ),
		),
		array(
			'id'          => 'toc_enable',
			'group_id'    => 'posts',
			'type'        => 'switcher',
			'label'       => __( 'Enable table of contents', 'lerm' ),
			'description' => __( 'Auto-generate a TOC from H2/H3 headings inside post content.', 'lerm' ),
			'group'       => __( 'Table of contents', 'lerm' ),
			'default'     => false,
		),
		array(
			'id'               => 'toc_min_headings',
			'group_id'         => 'posts',
			'type'             => 'number',
			'label'            => __( 'Minimum headings required', 'lerm' ),
			'description'      => __( 'The TOC stays hidden when a post has fewer headings than this value.', 'lerm' ),
			'group'            => __( 'Table of contents', 'lerm' ),
			'default'          => 3,
			'min'              => 1,
			'max'              => 20,
			'step'             => 1,
			'dependency_field' => 'toc_enable',
			'dependency_value' => '1',
		),
		array(
			'id'               => 'toc_position',
			'group_id'         => 'posts',
			'type'             => 'button_set',
			'label'            => __( 'TOC position', 'lerm' ),
			'group'            => __( 'Table of contents', 'lerm' ),
			'default'          => 'before_content',
			'choices'          => array(
				'before_content' => __( 'Above content', 'lerm' ),
				'sidebar'        => __( 'In sidebar', 'lerm' ),
				'floating'       => __( 'Floating panel', 'lerm' ),
			),
			'dependency_field' => 'toc_enable',
			'dependency_value' => '1',
		),
		array(
			'id'               => 'toc_collapsed',
			'group_id'         => 'posts',
			'type'             => 'switcher',
			'label'            => __( 'Collapse TOC by default', 'lerm' ),
			'group'            => __( 'Table of contents', 'lerm' ),
			'default'          => false,
			'dependency_field' => 'toc_enable',
			'dependency_value' => '1',
		),
		array(
			'id'       => 'post_likes_enable',
			'group_id' => 'posts',
			'type'     => 'switcher',
			'label'    => __( 'Show post like button', 'lerm' ),
			'group'    => __( 'Engagement', 'lerm' ),
			'default'  => true,
		),
		array(
			'id'       => 'comment_likes_enable',
			'group_id' => 'posts',
			'type'     => 'switcher',
			'label'    => __( 'Show comment like button', 'lerm' ),
			'group'    => __( 'Engagement', 'lerm' ),
			'default'  => true,
		),
		array(
			'id'       => 'post_views_enable',
			'group_id' => 'posts',
			'type'     => 'switcher',
			'label'    => __( 'Show post view count', 'lerm' ),
			'group'    => __( 'Engagement', 'lerm' ),
			'default'  => true,
		),
		array(
			'id'               => 'views_unique_only',
			'group_id'         => 'posts',
			'type'             => 'switcher',
			'label'            => __( 'Count unique visitors only', 'lerm' ),
			'description'      => __( 'Avoids inflating view counts with repeated reloads from the same browser session.', 'lerm' ),
			'group'            => __( 'Engagement', 'lerm' ),
			'default'          => true,
			'dependency_field' => 'post_views_enable',
			'dependency_value' => '1',
		),
		array(
			'id'       => 'share_position',
			'group_id' => 'posts',
			'type'     => 'button_set',
			'label'    => __( 'Share button position', 'lerm' ),
			'group'    => __( 'Sharing & copyright', 'lerm' ),
			'default'  => 'bottom',
			'choices'  => array(
				'top'    => __( 'Above content', 'lerm' ),
				'bottom' => __( 'Below content', 'lerm' ),
				'both'   => __( 'Both', 'lerm' ),
				'none'   => __( 'Hidden', 'lerm' ),
			),
		),
		array(
			'id'       => 'share_show_count',
			'group_id' => 'posts',
			'type'     => 'switcher',
			'label'    => __( 'Show share count', 'lerm' ),
			'group'    => __( 'Sharing & copyright', 'lerm' ),
			'default'  => false,
		),
		array(
			'id'          => 'post_copyright_enable',
			'group_id'    => 'posts',
			'type'        => 'switcher',
			'label'       => __( 'Show copyright / repost notice', 'lerm' ),
			'description' => __( 'Displays a copyright reminder and permalink block beneath single posts.', 'lerm' ),
			'group'       => __( 'Sharing & copyright', 'lerm' ),
			'default'     => true,
		),
		array(
			'id'               => 'post_copyright_text',
			'group_id'         => 'posts',
			'type'             => 'textarea',
			'label'            => __( 'Custom copyright text', 'lerm' ),
			'description'      => __( 'Overrides the default copyright message. Leave empty to use the theme default.', 'lerm' ),
			'group'            => __( 'Sharing & copyright', 'lerm' ),
			'default'          => '',
			'rows'             => 4,
			'placeholder'      => __( 'This article was published by ... Please credit the original source when reposting.', 'lerm' ),
			'dependency_field' => 'post_copyright_enable',
			'dependency_value' => '1',
		),
		//switching to a more flexible group field for sidebar management since the old static select fields were getting unwieldy with the addition of multiple new sidebars and the possibility of user-created sidebars.
			array(
				'id'          => 'register_sidebars',
				'group_id'    => 'sidebars',
				'type'        => 'group',
				'label'       => __( 'Custom sidebars', 'lerm' ),
				'description' => __( 'Additional sidebars registered by the theme. Save once before assigning them elsewhere.', 'lerm' ),
				'group'       => __( 'Custom sidebars', 'lerm' ),
				'default'     => array(),
				'button_text' => __( 'Add sidebar', 'lerm' ),
				'fields'      => array(
					array(
						'id'          => 'sidebar_title',
						'type'        => 'text',
						'label'       => __( 'Sidebar name', 'lerm' ),
						'description' => __( 'Human-friendly name shown in Widgets and Customizer panels.', 'lerm' ),
						'default'     => '',
						'placeholder' => __( 'Example: Article sidebar', 'lerm' ),
					),
				),
			),
		array(
			'id'          => 'single_sidebar_select',
			'group_id'    => 'sidebars',
			'type'        => 'select',
			'label'       => __( 'Single post sidebar', 'lerm' ),
			'description' => __( 'Sidebar used on single post pages.', 'lerm' ),
			'group'       => __( 'Sidebar assignments', 'lerm' ),
			'default'     => 'home-sidebar',
			'choices'     => array( OptionsPageDefinition::class, 'sidebar_choices' ),
		),
		array(
			'id'          => 'blog_sidebar_select',
			'group_id'    => 'sidebars',
			'type'        => 'select',
			'label'       => __( 'Blog archive sidebar', 'lerm' ),
			'description' => __( 'Sidebar used on blog archives and home loops.', 'lerm' ),
			'group'       => __( 'Sidebar assignments', 'lerm' ),
			'default'     => 'home-sidebar',
			'choices'     => array( OptionsPageDefinition::class, 'sidebar_choices' ),
		),
		array(
			'id'          => 'front_page_sidebar',
			'group_id'    => 'sidebars',
			'type'        => 'select',
			'label'       => __( 'Front page sidebar', 'lerm' ),
			'description' => __( 'Sidebar used on the static front page template.', 'lerm' ),
			'group'       => __( 'Sidebar assignments', 'lerm' ),
			'default'     => 'home-sidebar',
			'choices'     => array( OptionsPageDefinition::class, 'sidebar_choices' ),
		),
		array(
			'id'          => 'page_sidebar',
			'group_id'    => 'sidebars',
			'type'        => 'select',
			'label'       => __( 'Static page sidebar', 'lerm' ),
			'description' => __( 'Sidebar used on standard WordPress pages.', 'lerm' ),
			'group'       => __( 'Sidebar assignments', 'lerm' ),
			'default'     => 'home-sidebar',
			'choices'     => array( OptionsPageDefinition::class, 'sidebar_choices' ),
		),
		array(
			'id'          => 'comment_excerpt_length',
			'group_id'    => 'sidebars',
			'type'        => 'number',
			'label'       => __( 'Latest comments excerpt length', 'lerm' ),
			'description' => __( 'Controls excerpt length inside the latest comments widget.', 'lerm' ),
			'group'       => __( 'Widget settings', 'lerm' ),
			'default'     => 95,
			'min'         => 0,
			'max'         => 300,
			'step'        => 5,
		),
	),
);
