<?php // phpcs:disable WordPress.Files.FileName

declare( strict_types=1 );

use Lerm\OptionsFramework\Integrations\LermTheme\OptionsPageDefinition;

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

return array(
	'title'       => __( 'Content+', 'lerm' ),
	'description' => __( 'Archive presentation and single-post feature controls.', 'lerm' ),
	'fields'      => array(
		array(
			'id'          => 'summary_or_full',
			'type'        => 'radio',
			'label'       => __( 'Archive post display mode', 'lerm' ),
			'description' => __( 'Choose whether archive pages render full post bodies or excerpts.', 'lerm' ),
			'group'       => __( 'Archive cards', 'lerm' ),
			'default'     => 'content_summary',
			'choices'     => array(
				'content_full'    => __( 'Full content', 'lerm' ),
				'content_summary' => __( 'Excerpt only', 'lerm' ),
			),
		),
		array(
			'id'          => 'excerpt_length',
			'type'        => 'number',
			'label'       => __( 'Excerpt length (words)', 'lerm' ),
			'description' => __( 'Number of words shown in automatically generated excerpts.', 'lerm' ),
			'group'       => __( 'Archive cards', 'lerm' ),
			'default'     => 95,
			'min'         => 0,
			'max'         => 300,
			'step'        => 5,
		),
		array(
			'id'          => 'show_thumbnail',
			'type'        => 'switcher',
			'label'       => __( 'Show archive thumbnails', 'lerm' ),
			'description' => __( 'Displays featured or fallback thumbnails on archive cards.', 'lerm' ),
			'group'       => __( 'Archive cards', 'lerm' ),
			'default'     => true,
		),
		array(
			'id'               => 'thumbnail_gallery',
			'type'             => 'gallery',
			'label'            => __( 'Fallback thumbnail pool', 'lerm' ),
			'description'      => __( 'Images used when a post does not have a featured image.', 'lerm' ),
			'group'            => __( 'Archive cards', 'lerm' ),
			'default'          => array(),
			'dependency_field' => 'show_thumbnail',
			'dependency_value' => '1',
		),
		array(
			'id'          => 'cat_exclude',
			'type'        => 'checkbox_list',
			'label'       => __( 'Exclude categories', 'lerm' ),
			'description' => __( 'Posts in these categories will not appear on the main blog archive.', 'lerm' ),
			'group'       => __( 'Archive cards', 'lerm' ),
			'default'     => array(),
			'choices'     => array( OptionsPageDefinition::class, 'category_choices' ),
		),
		array(
			'id'          => 'load_more',
			'type'        => 'switcher',
			'label'       => __( 'Ajax "Load more" pagination', 'lerm' ),
			'description' => __( 'Replaces standard archive pagination with a load-more button.', 'lerm' ),
			'group'       => __( 'Archive cards', 'lerm' ),
			'default'     => false,
		),
		array(
			'id'      => 'loading_animate',
			'type'    => 'switcher',
			'label'   => __( 'Archive card entrance animation', 'lerm' ),
			'group'   => __( 'Archive cards', 'lerm' ),
			'default' => false,
		),
		array(
			'id'          => 'summary_meta',
			'type'        => 'sorter',
			'label'       => __( 'Archive meta items', 'lerm' ),
			'description' => __( 'Drag to set order, then tick the items that should appear below archive cards.', 'lerm' ),
			'group'       => __( 'Archive cards', 'lerm' ),
			'default'     => OptionsPageDefinition::summary_meta_default(),
			'choices'     => array( OptionsPageDefinition::class, 'post_meta_choices' ),
		),
		array(
			'id'      => 'post_navigation',
			'type'    => 'switcher',
			'label'   => __( 'Previous / next post navigation', 'lerm' ),
			'group'   => __( 'Single post', 'lerm' ),
			'default' => true,
		),
		array(
			'id'      => 'disable_pingback',
			'type'    => 'switcher',
			'label'   => __( 'Disable pingbacks', 'lerm' ),
			'group'   => __( 'Single post', 'lerm' ),
			'default' => false,
		),
		array(
			'id'          => 'enable_code_highlight',
			'type'        => 'switcher',
			'label'       => __( 'Syntax highlighting', 'lerm' ),
			'description' => __( 'Enable Prism.js highlighting for code blocks inside posts.', 'lerm' ),
			'group'       => __( 'Single post', 'lerm' ),
			'default'     => false,
		),
		array(
			'id'          => 'author_bio',
			'type'        => 'switcher',
			'label'       => __( 'Author bio box', 'lerm' ),
			'description' => __( 'Show the author biography card below single posts.', 'lerm' ),
			'group'       => __( 'Single post', 'lerm' ),
			'default'     => false,
		),
		array(
			'id'      => 'related_posts',
			'type'    => 'switcher',
			'label'   => __( 'Show related posts', 'lerm' ),
			'group'   => __( 'Single post', 'lerm' ),
			'default' => false,
		),
		array(
			'id'               => 'related_number',
			'type'             => 'number',
			'label'            => __( 'Related posts count', 'lerm' ),
			'group'            => __( 'Single post', 'lerm' ),
			'default'          => 5,
			'min'              => 1,
			'max'              => 12,
			'step'             => 1,
			'dependency_field' => 'related_posts',
			'dependency_value' => '1',
		),
		array(
			'id'          => 'single_top',
			'type'        => 'sorter',
			'label'       => __( 'Header meta items', 'lerm' ),
			'description' => __( 'Controls the post meta shown above the article body.', 'lerm' ),
			'group'       => __( 'Single post meta', 'lerm' ),
			'default'     => OptionsPageDefinition::single_top_default(),
			'choices'     => array( OptionsPageDefinition::class, 'post_meta_choices' ),
		),
		array(
			'id'          => 'single_bottom',
			'type'        => 'sorter',
			'label'       => __( 'Footer meta items', 'lerm' ),
			'description' => __( 'Controls the post meta shown below the article body.', 'lerm' ),
			'group'       => __( 'Single post meta', 'lerm' ),
			'default'     => OptionsPageDefinition::single_bottom_default(),
			'choices'     => array( OptionsPageDefinition::class, 'post_meta_choices' ),
		),
		array(
			'id'          => 'toc_enable',
			'type'        => 'switcher',
			'label'       => __( 'Enable table of contents', 'lerm' ),
			'description' => __( 'Auto-generate a TOC from H2/H3 headings inside post content.', 'lerm' ),
			'group'       => __( 'Table of contents', 'lerm' ),
			'default'     => false,
		),
		array(
			'id'               => 'toc_min_headings',
			'type'             => 'number',
			'label'            => __( 'Minimum headings required', 'lerm' ),
			'description'      => __( 'The TOC stays hidden when a post has fewer headings than this value.', 'lerm' ),
			'group'            => __( 'Table of contents', 'lerm' ),
			'default'          => 3,
			'min'              => 1,
			'max'              => 20,
			'step'             => 1,
			'dependency_field' => 'toc_enable',
			'dependency_value' => '1',
		),
		array(
			'id'               => 'toc_position',
			'type'             => 'button_set',
			'label'            => __( 'TOC position', 'lerm' ),
			'group'            => __( 'Table of contents', 'lerm' ),
			'default'          => 'before_content',
			'choices'          => array(
				'before_content' => __( 'Above content', 'lerm' ),
				'sidebar'        => __( 'In sidebar', 'lerm' ),
				'floating'       => __( 'Floating panel', 'lerm' ),
			),
			'dependency_field' => 'toc_enable',
			'dependency_value' => '1',
		),
		array(
			'id'               => 'toc_collapsed',
			'type'             => 'switcher',
			'label'            => __( 'Collapse TOC by default', 'lerm' ),
			'group'            => __( 'Table of contents', 'lerm' ),
			'default'          => false,
			'dependency_field' => 'toc_enable',
			'dependency_value' => '1',
		),
		array(
			'id'      => 'post_likes_enable',
			'type'    => 'switcher',
			'label'   => __( 'Show post like button', 'lerm' ),
			'group'   => __( 'Engagement', 'lerm' ),
			'default' => true,
		),
		array(
			'id'      => 'comment_likes_enable',
			'type'    => 'switcher',
			'label'   => __( 'Show comment like button', 'lerm' ),
			'group'   => __( 'Engagement', 'lerm' ),
			'default' => true,
		),
		array(
			'id'      => 'post_views_enable',
			'type'    => 'switcher',
			'label'   => __( 'Show post view count', 'lerm' ),
			'group'   => __( 'Engagement', 'lerm' ),
			'default' => true,
		),
		array(
			'id'               => 'views_unique_only',
			'type'             => 'switcher',
			'label'            => __( 'Count unique visitors only', 'lerm' ),
			'description'      => __( 'Avoids inflating view counts with repeated reloads from the same browser session.', 'lerm' ),
			'group'            => __( 'Engagement', 'lerm' ),
			'default'          => true,
			'dependency_field' => 'post_views_enable',
			'dependency_value' => '1',
		),
		array(
			'id'      => 'share_position',
			'type'    => 'button_set',
			'label'   => __( 'Share button position', 'lerm' ),
			'group'   => __( 'Sharing & copyright', 'lerm' ),
			'default' => 'bottom',
			'choices' => array(
				'top'    => __( 'Above content', 'lerm' ),
				'bottom' => __( 'Below content', 'lerm' ),
				'both'   => __( 'Both', 'lerm' ),
				'none'   => __( 'Hidden', 'lerm' ),
			),
		),
		array(
			'id'      => 'share_show_count',
			'type'    => 'switcher',
			'label'   => __( 'Show share count', 'lerm' ),
			'group'   => __( 'Sharing & copyright', 'lerm' ),
			'default' => false,
		),
		array(
			'id'          => 'post_copyright_enable',
			'type'        => 'switcher',
			'label'       => __( 'Show copyright / repost notice', 'lerm' ),
			'description' => __( 'Displays a copyright reminder and permalink block beneath single posts.', 'lerm' ),
			'group'       => __( 'Sharing & copyright', 'lerm' ),
			'default'     => true,
		),
		array(
			'id'               => 'post_copyright_text',
			'type'             => 'textarea',
			'label'            => __( 'Custom copyright text', 'lerm' ),
			'description'      => __( 'Overrides the default copyright message. Leave empty to use the theme default.', 'lerm' ),
			'group'            => __( 'Sharing & copyright', 'lerm' ),
			'default'          => '',
			'rows'             => 4,
			'placeholder'      => __( 'This article was published by ... Please credit the original source when reposting.', 'lerm' ),
			'dependency_field' => 'post_copyright_enable',
			'dependency_value' => '1',
		),
	),
);
