<?php // phpcs:disable WordPress.Files.FileName

declare( strict_types=1 );

use Lerm\OptionsFramework\Integrations\LermTheme\OptionsPageDefinition;

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

return array(
	'title'       => __( 'SEO', 'lerm' ),
	'description' => __( 'Meta output, sitemap exclusions, breadcrumb markup, and Baidu integrations migrated from the remaining CSF SEO tabs.', 'lerm' ),
	'fields'      => array(
		array(
			'id'          => 'keywords',
			'type'        => 'text',
			'label'       => __( 'Default keywords', 'lerm' ),
			'description' => __( 'Comma-separated keywords written into the home page meta tags.', 'lerm' ),
			'group'       => __( 'Meta & titles', 'lerm' ),
			'default'     => '',
			'placeholder' => __( 'WordPress, theme, blog', 'lerm' ),
		),
		array(
			'id'          => 'seo_description',
			'type'        => 'textarea',
			'label'       => __( 'Default description', 'lerm' ),
			'description' => __( 'Written into the home page meta description tag.', 'lerm' ),
			'group'       => __( 'Meta & titles', 'lerm' ),
			'default'     => '',
			'rows'        => 3,
			'placeholder' => __( 'A short description of your site.', 'lerm' ),
		),
		array(
			'id'          => 'title_sep',
			'type'        => 'select',
			'label'       => __( 'Title separator', 'lerm' ),
			'description' => __( 'Character placed between the page title and the site name.', 'lerm' ),
			'group'       => __( 'Meta & titles', 'lerm' ),
			'default'     => '|',
			'choices'     => array(
				'-'        => '-',
				'&ndash;'  => '&ndash;',
				'&mdash;'  => '&mdash;',
				':'        => ':',
				'&middot;' => '&middot;',
				'&bull;'   => '&bull;',
				'*'        => '*',
				'&#8902;'  => '&#8902;',
				'|'        => '|',
				'~'        => '~',
				'&laquo;'  => '&laquo;',
				'&raquo;'  => '&raquo;',
				'&gt;'     => '&gt;',
			),
		),
		array(
			'id'          => 'title_structure',
			'type'        => 'select',
			'label'       => __( 'Home page title order', 'lerm' ),
			'description' => __( 'Select the pieces used for the home page <title>. Multiple values are stored as an ordered list.', 'lerm' ),
			'group'       => __( 'Meta & titles', 'lerm' ),
			'default'     => array( 'title', 'separator', 'tagline' ),
			'multiple'    => true,
			'choices'     => array( OptionsPageDefinition::class, 'title_structure_choices' ),
		),
		array(
			'id'          => 'post_title_structure',
			'type'        => 'select',
			'label'       => __( 'Post title order', 'lerm' ),
			'description' => __( 'Select the pieces used for single-post <title> output.', 'lerm' ),
			'group'       => __( 'Meta & titles', 'lerm' ),
			'default'     => array( 'post_title', 'separator', 'title' ),
			'multiple'    => true,
			'choices'     => array( OptionsPageDefinition::class, 'title_structure_choices' ),
		),
		array(
			'id'          => 'page_title_structure',
			'type'        => 'select',
			'label'       => __( 'Page title order', 'lerm' ),
			'description' => __( 'Select the pieces used for static-page <title> output.', 'lerm' ),
			'group'       => __( 'Meta & titles', 'lerm' ),
			'default'     => array( 'page_title', 'separator', 'title' ),
			'multiple'    => true,
			'choices'     => array( OptionsPageDefinition::class, 'title_structure_choices' ),
		),
		array(
			'id'          => 'html_slug',
			'type'        => 'switcher',
			'label'       => __( 'Append .html to page URLs', 'lerm' ),
			'description' => __( 'After changing this, re-save your WordPress permalink settings.', 'lerm' ),
			'group'       => __( 'Meta & titles', 'lerm' ),
			'default'     => false,
		),
		array(
			'id'          => 'sitemap_enable',
			'type'        => 'switcher',
			'label'       => __( 'Enable XML sitemap', 'lerm' ),
			'description' => __( 'Outputs the theme sitemap endpoint and honours the exclusions below.', 'lerm' ),
			'group'       => __( 'Sitemap', 'lerm' ),
			'default'     => true,
		),
		array(
			'id'               => 'exclude_post_types',
			'type'             => 'checkbox_list',
			'label'            => __( 'Exclude content types', 'lerm' ),
			'description'      => __( 'Selected entities will be omitted from the sitemap.', 'lerm' ),
			'group'            => __( 'Sitemap', 'lerm' ),
			'default'          => array(),
			'choices'          => array( OptionsPageDefinition::class, 'sitemap_type_choices' ),
			'dependency_field' => 'sitemap_enable',
			'dependency_value' => '1',
		),
		array(
			'id'               => 'exclude_categories',
			'type'             => 'checkbox_list',
			'label'            => __( 'Exclude specific categories', 'lerm' ),
			'group'            => __( 'Sitemap', 'lerm' ),
			'default'          => array(),
			'choices'          => array( OptionsPageDefinition::class, 'category_choices' ),
			'dependency_field' => 'sitemap_enable',
			'dependency_value' => '1',
		),
		array(
			'id'               => 'exclude_tags',
			'type'             => 'checkbox_list',
			'label'            => __( 'Exclude specific tags', 'lerm' ),
			'group'            => __( 'Sitemap', 'lerm' ),
			'default'          => array(),
			'choices'          => array( OptionsPageDefinition::class, 'tag_choices' ),
			'dependency_field' => 'sitemap_enable',
			'dependency_value' => '1',
		),
		array(
			'id'               => 'exclude_page',
			'type'             => 'checkbox_list',
			'label'            => __( 'Exclude specific pages', 'lerm' ),
			'group'            => __( 'Sitemap', 'lerm' ),
			'default'          => array(),
			'choices'          => array( OptionsPageDefinition::class, 'page_checkbox_choices' ),
			'dependency_field' => 'sitemap_enable',
			'dependency_value' => '1',
		),
		array(
			'id'               => 'exclude_post',
			'type'             => 'checkbox_list',
			'label'            => __( 'Exclude specific posts', 'lerm' ),
			'group'            => __( 'Sitemap', 'lerm' ),
			'default'          => array(),
			'choices'          => array( OptionsPageDefinition::class, 'post_choices' ),
			'dependency_field' => 'sitemap_enable',
			'dependency_value' => '1',
		),
		array(
			'id'          => 'breadcrumb_container',
			'type'        => 'button_set',
			'label'       => __( 'Wrapper element', 'lerm' ),
			'description' => __( 'HTML element used to wrap the breadcrumb trail.', 'lerm' ),
			'group'       => __( 'Breadcrumb', 'lerm' ),
			'default'     => 'nav',
			'choices'     => array(
				'nav' => 'nav',
				'div' => 'div',
			),
		),
		array(
			'id'      => 'breadcrumb_list_tag',
			'type'    => 'button_set',
			'label'   => __( 'List element', 'lerm' ),
			'group'   => __( 'Breadcrumb', 'lerm' ),
			'default' => 'ol',
			'choices' => array(
				'ol'  => 'ol',
				'ul'  => 'ul',
				'div' => 'div',
			),
		),
		array(
			'id'      => 'breadcrumb_item_tag',
			'type'    => 'button_set',
			'label'   => __( 'Item element', 'lerm' ),
			'group'   => __( 'Breadcrumb', 'lerm' ),
			'default' => 'li',
			'choices' => array(
				'li'   => 'li',
				'span' => 'span',
			),
		),
		array(
			'id'          => 'breadcrumb_separator',
			'type'        => 'text',
			'label'       => __( 'Separator', 'lerm' ),
			'description' => __( 'Character shown between breadcrumb items.', 'lerm' ),
			'group'       => __( 'Breadcrumb', 'lerm' ),
			'default'     => '/',
		),
		array(
			'id'      => 'breadcrumb_before',
			'type'    => 'text',
			'label'   => __( 'Before text', 'lerm' ),
			'group'   => __( 'Breadcrumb', 'lerm' ),
			'default' => '',
		),
		array(
			'id'      => 'breadcrumb_after',
			'type'    => 'text',
			'label'   => __( 'After text', 'lerm' ),
			'group'   => __( 'Breadcrumb', 'lerm' ),
			'default' => '',
		),
		array(
			'id'      => 'breadcrumb_front_show',
			'type'    => 'switcher',
			'label'   => __( 'Show on front page', 'lerm' ),
			'group'   => __( 'Breadcrumb', 'lerm' ),
			'default' => false,
		),
		array(
			'id'      => 'breadcrumb_show_title',
			'type'    => 'switcher',
			'label'   => __( 'Include current page title', 'lerm' ),
			'group'   => __( 'Breadcrumb', 'lerm' ),
			'default' => true,
		),
		array(
			'id'          => 'baidu_tongji',
			'type'        => 'code_editor',
			'label'       => __( 'Baidu Analytics code', 'lerm' ),
			'description' => __( 'Paste the full Baidu Tongji script tag. It will be output before </head>.', 'lerm' ),
			'group'       => __( 'Analytics & submission', 'lerm' ),
			'default'     => '',
			'rows'        => 8,
		),
		array(
			'id'          => 'baidu_submit',
			'type'        => 'switcher',
			'label'       => __( 'Enable Baidu URL auto-submission', 'lerm' ),
			'description' => __( 'Automatically pushes new post URLs to Baidu Search.', 'lerm' ),
			'group'       => __( 'Analytics & submission', 'lerm' ),
			'default'     => false,
		),
		array(
			'id'               => 'submit_url',
			'type'             => 'url',
			'label'            => __( 'Push API endpoint URL', 'lerm' ),
			'group'            => __( 'Analytics & submission', 'lerm' ),
			'default'          => '',
			'dependency_field' => 'baidu_submit',
			'dependency_value' => '1',
			'placeholder'      => 'https://data.zz.baidu.com/urls?site=example.com&token=xxxx',
		),
		array(
			'id'               => 'submit_token',
			'type'             => 'text',
			'label'            => __( 'Push API token', 'lerm' ),
			'group'            => __( 'Analytics & submission', 'lerm' ),
			'default'          => '',
			'dependency_field' => 'baidu_submit',
			'dependency_value' => '1',
		),
	),
);
