<?php // phpcs:disable WordPress.Files.FileName

declare( strict_types=1 );

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

return array(
	'title'           => __( 'Appearance', 'lerm' ),
	'description'     => __( 'Layout, colors, typography, and advanced styling settings previously split across multiple appearance tabs.', 'lerm' ),
	'use_subsections' => true,
	'groups'          => array(
		array(
			'id'     => 'layout',
			'label'  => __( 'Layout', 'lerm' ),
			'fields' => array(
				array(
					'id'            => 'layout_style',
					'type'          => 'button_set',
					'label'         => __( 'Container style', 'lerm' ),
					'description'   => __( 'Wide uses the full browser width, Boxed centers the whole page, Separate keeps content and sidebar visually detached.', 'lerm' ),
					'group_heading' => __( 'Container style', 'lerm' ),
					'default'       => 'separate-layout',
					'choices'       => array(
						'wide-layout'     => __( 'Wide', 'lerm' ),
						'boxed-layout'    => __( 'Boxed', 'lerm' ),
						'separate-layout' => __( 'Separate', 'lerm' ),
					),
				),
				array(
					'id'            => 'site_width',
					'type'          => 'number',
					'label'         => __( 'Container width (px)', 'lerm' ),
					'description'   => __( 'Maximum width of the main content container outside boxed mode.', 'lerm' ),
					'group_heading' => __( 'Container style', 'lerm' ),
					'default'       => 1140,
					'min'           => 600,
					'max'           => 4096,
					'step'          => 1,
				),
				array(
					'id'               => 'boxed_width',
					'type'             => 'number',
					'label'            => __( 'Box width (px)', 'lerm' ),
					'description'      => __( 'Width of the centered page box in boxed mode.', 'lerm' ),
					'group_heading'    => __( 'Container style', 'lerm' ),
					'default'          => 1140,
					'min'              => 600,
					'max'              => 4096,
					'step'             => 1,
					'dependency_field' => 'layout_style',
					'dependency_value' => 'boxed-layout',
				),
				array(
					'id'               => 'outside_bg_color',
					'type'             => 'color',
					'label'            => __( 'Box outer background', 'lerm' ),
					'description'      => __( 'Background colour outside the main box in boxed mode.', 'lerm' ),
					'group_heading'    => __( 'Container style', 'lerm' ),
					'default'          => '#ebebeb',
					'dependency_field' => 'layout_style',
					'dependency_value' => 'boxed-layout',
				),
				array(
					'id'               => 'inner_bg_color',
					'type'             => 'color',
					'label'            => __( 'Box inner background', 'lerm' ),
					'description'      => __( 'Background colour of the centered page box in boxed mode.', 'lerm' ),
					'group_heading'    => __( 'Container style', 'lerm' ),
					'default'          => '#ffffff',
					'dependency_field' => 'layout_style',
					'dependency_value' => 'boxed-layout',
				),
				array(
					'id'            => 'global_layout',
					'type'          => 'button_set',
					'label'         => __( 'Default sidebar position', 'lerm' ),
					'description'   => __( 'Full-width, narrow full-width, sidebar on the left, or sidebar on the right.', 'lerm' ),
					'group_heading' => __( 'Sidebar layout', 'lerm' ),
					'default'       => 'layout-2c-r',
					'choices'       => array(
						'layout-1c'        => __( 'Full width', 'lerm' ),
						'layout-1c-narrow' => __( 'Narrow full width', 'lerm' ),
						'layout-2c-l'      => __( 'Sidebar left', 'lerm' ),
						'layout-2c-r'      => __( 'Sidebar right', 'lerm' ),
					),
				),
				array(
					'id'            => 'affix',
					'type'          => 'switcher',
					'label'         => __( 'Sticky sidebar', 'lerm' ),
					'description'   => __( 'Keeps the sidebar visible while visitors scroll past long content.', 'lerm' ),
					'group_heading' => __( 'Sidebar layout', 'lerm' ),
					'default'       => false,
				),
				array(
					'id'            => 'content_width',
					'type'          => 'number',
					'label'         => __( 'Content column width (%)', 'lerm' ),
					'description'   => __( 'Width of the main content column when a sidebar is present.', 'lerm' ),
					'group_heading' => __( 'Sidebar layout', 'lerm' ),
					'default'       => 66.6666666667,
					'cast'          => 'float',
					'min'           => 10,
					'max'           => 90,
					'step'          => 0.01,
				),
				array(
					'id'            => 'sidebar_width',
					'type'          => 'number',
					'label'         => __( 'Sidebar column width (%)', 'lerm' ),
					'description'   => __( 'Width of the sidebar column when the page uses a two-column layout.', 'lerm' ),
					'group_heading' => __( 'Sidebar layout', 'lerm' ),
					'default'       => 33.3333333333,
					'cast'          => 'float',
					'min'           => 10,
					'max'           => 90,
					'step'          => 0.01,
				),
			),
		),
		array(
			'id'     => 'colors',
			'label'  => __( 'Colors', 'lerm' ),
			'fields' => array(
				array(
					'id'            => 'primary_color',
					'type'          => 'fieldset',
					'label'         => __( 'Primary color', 'lerm' ),
					'description'   => __( 'Used for buttons, badges, and interactive accents.', 'lerm' ),
					'group_heading' => __( 'Brand colors', 'lerm' ),
					'default'       => array(
						'color'  => '#0084ba',
						'hover'  => '#0063aa',
						'active' => '#0063aa',
						'focus'  => '#0063aa',
					),
					'fields'        => array(
						array(
							'id'      => 'color',
							'type'    => 'color',
							'label'   => __( 'Base', 'lerm' ),
							'default' => '#0084ba',
						),
						array(
							'id'      => 'hover',
							'type'    => 'color',
							'label'   => __( 'Hover', 'lerm' ),
							'default' => '#0063aa',
						),
						array(
							'id'      => 'active',
							'type'    => 'color',
							'label'   => __( 'Active', 'lerm' ),
							'default' => '#0063aa',
						),
						array(
							'id'      => 'focus',
							'type'    => 'color',
							'label'   => __( 'Focus', 'lerm' ),
							'default' => '#0063aa',
						),
					),
				),
				array(
					'id'            => 'link_color',
					'type'          => 'fieldset',
					'label'         => __( 'Link color', 'lerm' ),
					'description'   => __( 'Colour of anchors in article and page content.', 'lerm' ),
					'group_heading' => __( 'Brand colors', 'lerm' ),
					'default'       => array(
						'color'  => '#0084ba',
						'hover'  => '#0063aa',
						'active' => '#0063aa',
						'focus'  => '#0063aa',
					),
					'fields'        => array(
						array(
							'id'      => 'color',
							'type'    => 'color',
							'label'   => __( 'Base', 'lerm' ),
							'default' => '#0084ba',
						),
						array(
							'id'      => 'hover',
							'type'    => 'color',
							'label'   => __( 'Hover', 'lerm' ),
							'default' => '#0063aa',
						),
						array(
							'id'      => 'active',
							'type'    => 'color',
							'label'   => __( 'Active', 'lerm' ),
							'default' => '#0063aa',
						),
						array(
							'id'      => 'focus',
							'type'    => 'color',
							'label'   => __( 'Focus', 'lerm' ),
							'default' => '#0063aa',
						),
					),
				),
				array(
					'id'            => 'body_background',
					'type'          => 'fieldset',
					'label'         => __( 'Body background', 'lerm' ),
					'description'   => __( 'Page background colour used across the whole site.', 'lerm' ),
					'group_heading' => __( 'Page background', 'lerm' ),
					'default'       => array(
						'background-color' => '#ffffff',
					),
					'fields'        => array(
						array(
							'id'      => 'background-color',
							'type'    => 'color',
							'label'   => __( 'Background color', 'lerm' ),
							'default' => '#ffffff',
						),
					),
				),
				array(
					'id'            => 'content_background',
					'type'          => 'fieldset',
					'label'         => __( 'Card / content background', 'lerm' ),
					'description'   => __( 'Background colour used by article cards and content surfaces.', 'lerm' ),
					'group_heading' => __( 'Page background', 'lerm' ),
					'default'       => array(
						'background-color' => '#ffffff',
					),
					'fields'        => array(
						array(
							'id'      => 'background-color',
							'type'    => 'color',
							'label'   => __( 'Background color', 'lerm' ),
							'default' => '#ffffff',
						),
					),
				),
				array(
					'id'            => 'site_header_border',
					'type'          => 'fieldset',
					'label'         => __( 'Header border', 'lerm' ),
					'description'   => __( 'Border drawn around the site header. Most themes only use the bottom edge.', 'lerm' ),
					'group_heading' => __( 'Header & navigation', 'lerm' ),
					'default'       => array(
						'top'    => '0',
						'bottom' => '1',
						'left'   => '0',
						'right'  => '0',
						'style'  => 'solid',
						'color'  => '#82828244',
					),
					'fields'        => array(
						array(
							'id'      => 'top',
							'type'    => 'number',
							'label'   => __( 'Top (px)', 'lerm' ),
							'default' => 0,
							'min'     => 0,
							'max'     => 20,
							'step'    => 1,
						),
						array(
							'id'      => 'bottom',
							'type'    => 'number',
							'label'   => __( 'Bottom (px)', 'lerm' ),
							'default' => 1,
							'min'     => 0,
							'max'     => 20,
							'step'    => 1,
						),
						array(
							'id'      => 'left',
							'type'    => 'number',
							'label'   => __( 'Left (px)', 'lerm' ),
							'default' => 0,
							'min'     => 0,
							'max'     => 20,
							'step'    => 1,
						),
						array(
							'id'      => 'right',
							'type'    => 'number',
							'label'   => __( 'Right (px)', 'lerm' ),
							'default' => 0,
							'min'     => 0,
							'max'     => 20,
							'step'    => 1,
						),
						array(
							'id'      => 'style',
							'type'    => 'select',
							'label'   => __( 'Style', 'lerm' ),
							'default' => 'solid',
							'choices' => array(
								'solid'  => __( 'Solid', 'lerm' ),
								'dashed' => __( 'Dashed', 'lerm' ),
								'dotted' => __( 'Dotted', 'lerm' ),
								'double' => __( 'Double', 'lerm' ),
							),
						),
						array(
							'id'      => 'color',
							'type'    => 'color',
							'label'   => __( 'Color', 'lerm' ),
							'default' => '#82828244',
						),
					),
				),
				array(
					'id'            => 'navbar_link_color',
					'type'          => 'fieldset',
					'label'         => __( 'Nav link color', 'lerm' ),
					'description'   => __( 'Colour of navigation links and dropdown items.', 'lerm' ),
					'group_heading' => __( 'Header & navigation', 'lerm' ),
					'default'       => array(
						'color' => '#828282',
						'hover' => '#0084ba',
					),
					'fields'        => array(
						array(
							'id'      => 'color',
							'type'    => 'color',
							'label'   => __( 'Base', 'lerm' ),
							'default' => '#828282',
						),
						array(
							'id'      => 'hover',
							'type'    => 'color',
							'label'   => __( 'Hover', 'lerm' ),
							'default' => '#0084ba',
						),
					),
				),
				array(
					'id'            => 'navbar_active_color',
					'type'          => 'fieldset',
					'label'         => __( 'Nav active item color', 'lerm' ),
					'description'   => __( 'Text and background colours for the active navigation item.', 'lerm' ),
					'group_heading' => __( 'Header & navigation', 'lerm' ),
					'default'       => array(
						'color'            => '#0084ba',
						'background_color' => '#ffffff',
					),
					'fields'        => array(
						array(
							'id'      => 'color',
							'type'    => 'color',
							'label'   => __( 'Text color', 'lerm' ),
							'default' => '#0084ba',
						),
						array(
							'id'      => 'background_color',
							'type'    => 'color',
							'label'   => __( 'Background color', 'lerm' ),
							'default' => '#ffffff',
						),
					),
				),
				array(
					'id'            => 'navbar_item_padding',
					'type'          => 'fieldset',
					'label'         => __( 'Nav item padding', 'lerm' ),
					'description'   => __( 'Vertical padding applied to each navigation link.', 'lerm' ),
					'group_heading' => __( 'Header & navigation', 'lerm' ),
					'default'       => array(
						'top'    => '1.5',
						'bottom' => '1.5',
						'unit'   => 'rem',
					),
					'fields'        => array(
						array(
							'id'      => 'top',
							'type'    => 'number',
							'label'   => __( 'Top', 'lerm' ),
							'default' => '1.5',
							'min'     => 0,
							'step'    => 0.1,
						),
						array(
							'id'      => 'bottom',
							'type'    => 'number',
							'label'   => __( 'Bottom', 'lerm' ),
							'default' => '1.5',
							'min'     => 0,
							'step'    => 0.1,
						),
						array(
							'id'      => 'left',
							'type'    => 'number',
							'label'   => __( 'Left', 'lerm' ),
							'default' => '',
							'min'     => 0,
							'step'    => 0.1,
						),
						array(
							'id'      => 'right',
							'type'    => 'number',
							'label'   => __( 'Right', 'lerm' ),
							'default' => '',
							'min'     => 0,
							'step'    => 0.1,
						),
						array(
							'id'      => 'unit',
							'type'    => 'select',
							'label'   => __( 'Unit', 'lerm' ),
							'default' => 'rem',
							'choices' => array(
								'rem' => 'rem',
								'em'  => 'em',
								'px'  => 'px',
							),
						),
					),
				),
				array(
					'id'            => 'widget_header_color',
					'type'          => 'fieldset',
					'label'         => __( 'Widget header color', 'lerm' ),
					'description'   => __( 'Text, background, and border colours of widget and card headers.', 'lerm' ),
					'group_heading' => __( 'Widget headers', 'lerm' ),
					'default'       => array(
						'color'            => '',
						'background_color' => '',
						'border_color'     => '',
					),
					'fields'        => array(
						array(
							'id'      => 'color',
							'type'    => 'color',
							'label'   => __( 'Text color', 'lerm' ),
							'default' => '',
						),
						array(
							'id'      => 'background_color',
							'type'    => 'color',
							'label'   => __( 'Background color', 'lerm' ),
							'default' => '',
						),
						array(
							'id'      => 'border_color',
							'type'    => 'color',
							'label'   => __( 'Border color', 'lerm' ),
							'default' => '',
						),
					),
				),
				array(
					'id'            => 'footer_widget_color',
					'type'          => 'fieldset',
					'label'         => __( 'Footer widgets area', 'lerm' ),
					'description'   => __( 'Text and background colours of the footer widgets zone.', 'lerm' ),
					'group_heading' => __( 'Footer', 'lerm' ),
					'default'       => array(
						'color'            => '#dddddd',
						'background_color' => '#333333',
					),
					'fields'        => array(
						array(
							'id'      => 'color',
							'type'    => 'color',
							'label'   => __( 'Text color', 'lerm' ),
							'default' => '#dddddd',
						),
						array(
							'id'      => 'background_color',
							'type'    => 'color',
							'label'   => __( 'Background color', 'lerm' ),
							'default' => '#333333',
						),
					),
				),
				array(
					'id'            => 'footer_bar_color',
					'type'          => 'fieldset',
					'label'         => __( 'Footer bar', 'lerm' ),
					'description'   => __( 'Text and background colours of the copyright strip.', 'lerm' ),
					'group_heading' => __( 'Footer', 'lerm' ),
					'default'       => array(
						'color'            => '#dddddd',
						'background_color' => '#555555',
					),
					'fields'        => array(
						array(
							'id'      => 'color',
							'type'    => 'color',
							'label'   => __( 'Text color', 'lerm' ),
							'default' => '#dddddd',
						),
						array(
							'id'      => 'background_color',
							'type'    => 'color',
							'label'   => __( 'Background color', 'lerm' ),
							'default' => '#555555',
						),
					),
				),
				array(
					'id'            => 'btn_primary',
					'type'          => 'fieldset',
					'label'         => __( 'Primary button (default state)', 'lerm' ),
					'description'   => __( 'Text, background, and border colours for primary buttons at rest.', 'lerm' ),
					'group_heading' => __( 'Buttons', 'lerm' ),
					'default'       => array(
						'color'            => '#0084ba',
						'background_color' => '',
						'border_color'     => '#0084ba',
					),
					'fields'        => array(
						array(
							'id'      => 'color',
							'type'    => 'color',
							'label'   => __( 'Text color', 'lerm' ),
							'default' => '#0084ba',
						),
						array(
							'id'      => 'background_color',
							'type'    => 'color',
							'label'   => __( 'Background color', 'lerm' ),
							'default' => '',
						),
						array(
							'id'      => 'border_color',
							'type'    => 'color',
							'label'   => __( 'Border color', 'lerm' ),
							'default' => '#0084ba',
						),
					),
				),
				array(
					'id'            => 'btn_primary_hover',
					'type'          => 'fieldset',
					'label'         => __( 'Primary button (hover state)', 'lerm' ),
					'description'   => __( 'Text, background, and border colours for primary buttons on hover.', 'lerm' ),
					'group_heading' => __( 'Buttons', 'lerm' ),
					'default'       => array(
						'color'            => '#ffffff',
						'background_color' => '#0084ba',
						'border_color'     => '#0084ba',
					),
					'fields'        => array(
						array(
							'id'      => 'color',
							'type'    => 'color',
							'label'   => __( 'Text color', 'lerm' ),
							'default' => '#ffffff',
						),
						array(
							'id'      => 'background_color',
							'type'    => 'color',
							'label'   => __( 'Background color', 'lerm' ),
							'default' => '#0084ba',
						),
						array(
							'id'      => 'border_color',
							'type'    => 'color',
							'label'   => __( 'Border color', 'lerm' ),
							'default' => '#0084ba',
						),
					),
				),
			),
		),
		array(
			'id'     => 'typography',
			'label'  => __( 'Typography', 'lerm' ),
			'fields' => array(
				array(
					'id'            => 'body_typography',
					'type'          => 'typography',
					'label'         => __( 'Body text', 'lerm' ),
					'description'   => __( 'Base typography applied to body copy and general content.', 'lerm' ),
					'group_heading' => __( 'Typography', 'lerm' ),
					'default'       => array(
						'font-weight' => '400',
						'color'       => '#5d6777',
						'font-size'   => '.875',
						'unit'        => 'rem',
					),
					'fields'        => array(
						array(
							'id'      => 'font-family',
							'type'    => 'text',
							'label'   => __( 'Font family', 'lerm' ),
							'default' => '',
						),
						array(
							'id'      => 'font-weight',
							'type'    => 'text',
							'label'   => __( 'Font weight', 'lerm' ),
							'default' => '400',
						),
						array(
							'id'      => 'color',
							'type'    => 'color',
							'label'   => __( 'Text color', 'lerm' ),
							'default' => '#5d6777',
						),
						array(
							'id'      => 'font-size',
							'type'    => 'text',
							'label'   => __( 'Font size', 'lerm' ),
							'default' => '.875',
						),
						array(
							'id'      => 'line-height',
							'type'    => 'text',
							'label'   => __( 'Line height', 'lerm' ),
							'default' => '',
						),
						array(
							'id'      => 'unit',
							'type'    => 'select',
							'label'   => __( 'Size unit', 'lerm' ),
							'default' => 'rem',
							'choices' => array(
								'rem' => 'rem',
								'em'  => 'em',
								'px'  => 'px',
							),
						),
					),
				),
				array(
					'id'            => 'menu_typography',
					'type'          => 'typography',
					'label'         => __( 'Navigation font', 'lerm' ),
					'description'   => __( 'Typography applied to the top navigation bar.', 'lerm' ),
					'group_heading' => __( 'Typography', 'lerm' ),
					'default'       => array(
						'font-weight' => '400',
						'color'       => '#5d6777',
						'font-size'   => '.875',
						'unit'        => 'rem',
						'line-height' => '1.5',
					),
					'fields'        => array(
						array(
							'id'      => 'font-family',
							'type'    => 'text',
							'label'   => __( 'Font family', 'lerm' ),
							'default' => '',
						),
						array(
							'id'      => 'font-weight',
							'type'    => 'text',
							'label'   => __( 'Font weight', 'lerm' ),
							'default' => '400',
						),
						array(
							'id'      => 'color',
							'type'    => 'color',
							'label'   => __( 'Text color', 'lerm' ),
							'default' => '#5d6777',
						),
						array(
							'id'      => 'font-size',
							'type'    => 'text',
							'label'   => __( 'Font size', 'lerm' ),
							'default' => '.875',
						),
						array(
							'id'      => 'line-height',
							'type'    => 'text',
							'label'   => __( 'Line height', 'lerm' ),
							'default' => '1.5',
						),
						array(
							'id'      => 'unit',
							'type'    => 'select',
							'label'   => __( 'Size unit', 'lerm' ),
							'default' => 'rem',
							'choices' => array(
								'rem' => 'rem',
								'em'  => 'em',
								'px'  => 'px',
							),
						),
					),
				),
			),
		),
		array(
			'id'     => 'advanced',
			'label'  => __( 'Advanced', 'lerm' ),
			'fields' => array(
				array(
					'id'            => 'custom_css',
					'type'          => 'code_editor',
					'label'         => __( 'Custom CSS', 'lerm' ),
					'description'   => __( 'CSS entered here is output in a style tag in the page head.', 'lerm' ),
					'group_heading' => __( 'Custom CSS', 'lerm' ),
					'default'       => '',
					'rows'          => 12,
				),
				array(
					'id'            => 'dark_mode_enable',
					'type'          => 'switcher',
					'label'         => __( 'Enable dark mode support', 'lerm' ),
					'description'   => __( 'Adds a visitor-facing toggle between light and dark themes.', 'lerm' ),
					'group_heading' => __( 'Dark mode', 'lerm' ),
					'default'       => false,
				),
				array(
					'id'               => 'dark_mode_default',
					'type'             => 'button_set',
					'label'            => __( 'Default color scheme', 'lerm' ),
					'description'      => __( 'Choose whether visitors start in light, dark, or system-following mode.', 'lerm' ),
					'group_heading'    => __( 'Dark mode', 'lerm' ),
					'default'          => 'system',
					'choices'          => array(
						'light'  => __( 'Light', 'lerm' ),
						'dark'   => __( 'Dark', 'lerm' ),
						'system' => __( 'Follow system', 'lerm' ),
					),
					'dependency_field' => 'dark_mode_enable',
					'dependency_value' => '1',
				),
				array(
					'id'               => 'dark_mode_toggle_position',
					'type'             => 'button_set',
					'label'            => __( 'Toggle button position', 'lerm' ),
					'description'      => __( 'Choose whether the dark-mode toggle lives in the navbar or as a floating sidebar button.', 'lerm' ),
					'group_heading'    => __( 'Dark mode', 'lerm' ),
					'default'          => 'navbar',
					'choices'          => array(
						'navbar'  => __( 'In navbar', 'lerm' ),
						'sidebar' => __( 'Floating button', 'lerm' ),
					),
					'dependency_field' => 'dark_mode_enable',
					'dependency_value' => '1',
				),
				array(
					'id'               => 'dark_bg_body',
					'type'             => 'color',
					'label'            => __( 'Body background', 'lerm' ),
					'description'      => __( 'Page-level background color in dark mode.', 'lerm' ),
					'group_heading'    => __( 'Dark palette', 'lerm' ),
					'default'          => '#1a1b1e',
					'dependency_field' => 'dark_mode_enable',
					'dependency_value' => '1',
				),
				array(
					'id'               => 'dark_bg_card',
					'type'             => 'color',
					'label'            => __( 'Card background', 'lerm' ),
					'description'      => __( 'Background color for cards and content surfaces in dark mode.', 'lerm' ),
					'group_heading'    => __( 'Dark palette', 'lerm' ),
					'default'          => '#25262b',
					'dependency_field' => 'dark_mode_enable',
					'dependency_value' => '1',
				),
				array(
					'id'               => 'dark_bg_header',
					'type'             => 'color',
					'label'            => __( 'Header background', 'lerm' ),
					'group_heading'    => __( 'Dark palette', 'lerm' ),
					'default'          => '#1f2023',
					'dependency_field' => 'dark_mode_enable',
					'dependency_value' => '1',
				),
				array(
					'id'               => 'dark_text',
					'type'             => 'color',
					'label'            => __( 'Body text color', 'lerm' ),
					'group_heading'    => __( 'Dark palette', 'lerm' ),
					'default'          => '#c1c2c5',
					'dependency_field' => 'dark_mode_enable',
					'dependency_value' => '1',
				),
				array(
					'id'               => 'dark_text_muted',
					'type'             => 'color',
					'label'            => __( 'Muted text color', 'lerm' ),
					'description'      => __( 'Used for secondary metadata, captions, and placeholders in dark mode.', 'lerm' ),
					'group_heading'    => __( 'Dark palette', 'lerm' ),
					'default'          => '#909296',
					'dependency_field' => 'dark_mode_enable',
					'dependency_value' => '1',
				),
				array(
					'id'               => 'dark_border',
					'type'             => 'color',
					'label'            => __( 'Border color', 'lerm' ),
					'group_heading'    => __( 'Dark palette', 'lerm' ),
					'default'          => '#373a40',
					'dependency_field' => 'dark_mode_enable',
					'dependency_value' => '1',
				),
				array(
					'id'               => 'dark_footer_bg',
					'type'             => 'color',
					'label'            => __( 'Footer widgets background', 'lerm' ),
					'group_heading'    => __( 'Dark palette', 'lerm' ),
					'default'          => '#141517',
					'dependency_field' => 'dark_mode_enable',
					'dependency_value' => '1',
				),
				array(
					'id'               => 'dark_bar_bg',
					'type'             => 'color',
					'label'            => __( 'Footer bar background', 'lerm' ),
					'group_heading'    => __( 'Dark palette', 'lerm' ),
					'default'          => '#101113',
					'dependency_field' => 'dark_mode_enable',
					'dependency_value' => '1',
				),
				array(
					'id'            => 'reading_progress',
					'type'          => 'switcher',
					'label'         => __( 'Show reading progress bar', 'lerm' ),
					'description'   => __( 'Displays a slim reading-progress bar at the very top of single posts.', 'lerm' ),
					'group_heading' => __( 'Reader UI', 'lerm' ),
					'default'       => false,
				),
				array(
					'id'               => 'reading_progress_color',
					'type'             => 'color',
					'label'            => __( 'Progress bar color', 'lerm' ),
					'group_heading'    => __( 'Reader UI', 'lerm' ),
					'default'          => '#0084ba',
					'dependency_field' => 'reading_progress',
					'dependency_value' => '1',
				),
				array(
					'id'               => 'reading_progress_height',
					'type'             => 'number',
					'label'            => __( 'Progress bar height (px)', 'lerm' ),
					'group_heading'    => __( 'Reader UI', 'lerm' ),
					'default'          => 3,
					'min'              => 1,
					'max'              => 10,
					'step'             => 1,
					'dependency_field' => 'reading_progress',
					'dependency_value' => '1',
				),
				array(
					'id'            => 'back_to_top',
					'type'          => 'switcher',
					'label'         => __( 'Show back-to-top button', 'lerm' ),
					'group_heading' => __( 'Utility buttons', 'lerm' ),
					'default'       => true,
				),
				array(
					'id'               => 'back_to_top_threshold',
					'type'             => 'number',
					'label'            => __( 'Back-to-top threshold (px)', 'lerm' ),
					'description'      => __( 'The button appears after the visitor scrolls this many pixels.', 'lerm' ),
					'group_heading'    => __( 'Utility buttons', 'lerm' ),
					'default'          => 400,
					'min'              => 100,
					'max'              => 2000,
					'step'             => 50,
					'dependency_field' => 'back_to_top',
					'dependency_value' => '1',
				),
				array(
					'id'            => 'qq_chat_enable',
					'type'          => 'switcher',
					'label'         => __( 'Show QQ live chat button', 'lerm' ),
					'group_heading' => __( 'Utility buttons', 'lerm' ),
					'default'       => false,
				),
				array(
					'id'               => 'qq_chat_number',
					'type'             => 'text',
					'label'            => __( 'QQ number', 'lerm' ),
					'description'      => __( 'Opens a QQ chat window when the floating button is clicked.', 'lerm' ),
					'group_heading'    => __( 'Utility buttons', 'lerm' ),
					'default'          => '',
					'placeholder'      => '825641026',
					'dependency_field' => 'qq_chat_enable',
					'dependency_value' => '1',
				),
			),
		),
	),
);
