<?php // phpcs:disable WordPress.Files.FileName

declare( strict_types=1 );

use Lerm\Theme\AdminConfig\ThemeOptionsDefinition;

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

return array(
	'title'           => __( 'Content', 'lerm' ),
	'description'     => __( 'Static-page content rules, search behaviour, and archive display settings.', 'lerm' ),
	'use_subsections' => true,
	'groups'          => array(
		array(
			'id'     => 'search',
			'label'  => __( 'Search behaviour', 'lerm' ),
			'fields' => array(
				array(
					'id'          => 'search_filter',
					'type'        => 'switcher',
					'label'       => __( 'Exclude pages from search results', 'lerm' ),
					'description' => __( 'When enabled, WordPress search only returns posts instead of mixing in static pages.', 'lerm' ),
					'group_heading' => __( 'Search behaviour', 'lerm' ),
					'default'     => true,
				),
				array(
					'id'          => 'search_results_per_page',
					'type'        => 'number',
					'label'       => __( 'Instant search results count', 'lerm' ),
					'description' => __( 'Maximum number of items shown in the instant search dropdown.', 'lerm' ),
					'group_heading' => __( 'Instant search', 'lerm' ),
					'default'     => 5,
					'min'         => 1,
					'max'         => 20,
					'step'        => 1,
				),
				array(
					'id'          => 'search_placeholder',
					'type'        => 'text',
					'label'       => __( 'Search box placeholder', 'lerm' ),
					'description' => __( 'Placeholder shown in the search form and instant search field.', 'lerm' ),
					'group_heading' => __( 'Instant search', 'lerm' ),
					'default'     => '',
					'placeholder' => __( 'Search...', 'lerm' ),
				),
			),
		),
		array(
			'id'     => 'carousel',
			'label'  => __( 'Carousel', 'lerm' ),
			'fields' => array(
				array(
					'id'          => 'slide_enable',
					'type'        => 'switcher',
					'label'       => __( 'Enable homepage slider', 'lerm' ),
					'description' => __( 'Shows the carousel block on the homepage when slides exist.', 'lerm' ),
					'group_heading' => __( 'Carousel', 'lerm' ),
					'default'     => false,
				),
				array(
					'id'               => 'slide_position',
					'type'             => 'button_set',
					'label'            => __( 'Slider position', 'lerm' ),
					'description'      => __( 'Controls how wide the homepage slider should be rendered.', 'lerm' ),
					'group_heading' => __( 'Carousel', 'lerm' ),
					'default'          => 'under_navbar',
					'choices'          => array(
						'under_navbar'  => __( 'Under navbar', 'lerm' ),
						'under_primary' => __( 'Content width', 'lerm' ),
						'full_width'    => __( 'Full width', 'lerm' ),
					),
					'dependency_field' => 'slide_enable',
					'dependency_value' => '1',
				),
				array(
					'id'               => 'slide_indicators',
					'type'             => 'switcher',
					'label'            => __( 'Show indicators', 'lerm' ),
					'description'      => __( 'Displays the small dots beneath the carousel.', 'lerm' ),
					'group_heading' => __( 'Carousel', 'lerm' ),
					'default'          => false,
					'dependency_field' => 'slide_enable',
					'dependency_value' => '1',
				),
				array(
					'id'               => 'slide_control',
					'type'             => 'switcher',
					'label'            => __( 'Show previous / next controls', 'lerm' ),
					'group_heading' => __( 'Carousel', 'lerm' ),
					'default'          => false,
					'dependency_field' => 'slide_enable',
					'dependency_value' => '1',
				),
				array(
					'id'               => 'slide_images',
					'type'             => 'group',
					'label'            => __( 'Slides', 'lerm' ),
					'description'      => __( 'Each slide can include an image, title, optional link, and caption text.', 'lerm' ),
					'group_heading' => __( 'Slides', 'lerm' ),
					'default'          => array(),
					'button_text'      => __( 'Add slide', 'lerm' ),
					'dependency_field' => 'slide_enable',
					'dependency_value' => '1',
					'fields'           => array(
						array(
							'id'          => 'image',
							'type'        => 'media',
							'label'       => __( 'Slide image', 'lerm' ),
							'description' => __( 'Main slide image displayed in the carousel.', 'lerm' ),
							'default'     => array(),
						),
						array(
							'id'          => 'title',
							'type'        => 'text',
							'label'       => __( 'Caption title', 'lerm' ),
							'default'     => '',
							'placeholder' => __( 'Hero title', 'lerm' ),
						),
						array(
							'id'          => 'url',
							'type'        => 'url',
							'label'       => __( 'Link URL', 'lerm' ),
							'default'     => '',
							'placeholder' => 'https://example.com/article',
						),
						array(
							'id'          => 'description',
							'type'        => 'textarea',
							'label'       => __( 'Caption text', 'lerm' ),
							'default'     => '',
							'rows'        => 3,
							'placeholder' => __( 'Short supporting text shown over the slide.', 'lerm' ),
						),
					),
				),
			),
		),
		array(
			'id'     => 'content_404',
			'label'  => __( '404 page', 'lerm' ),
			'fields' => array(
				array(
					'id'      => '404_title',
					'type'    => 'text',
					'label'   => __( 'Page title', 'lerm' ),
					'group_heading' => __( '404 page', 'lerm' ),
					'default' => __( '404 Not Found', 'lerm' ),
				),
				array(
					'id'      => '404_message',
					'type'    => 'textarea',
					'label'   => __( 'Error message', 'lerm' ),
					'group_heading' => __( '404 page', 'lerm' ),
					'default' => __( 'Sorry, the page you are looking for could not be found.', 'lerm' ),
					'rows'    => 3,
				),
				array(
					'id'      => '404_button_text',
					'type'    => 'text',
					'label'   => __( 'Button label', 'lerm' ),
					'group_heading' => __( '404 page', 'lerm' ),
					'default' => __( 'Back to home', 'lerm' ),
				),
				array(
					'id'          => '404_button_url',
					'type'        => 'url',
					'label'       => __( 'Button URL', 'lerm' ),
					'description' => __( 'Leave empty to send visitors back to the homepage.', 'lerm' ),
					'group_heading' => __( '404 page', 'lerm' ),
					'default'     => '',
					'placeholder' => home_url( '/' ),
				),
				array(
					'id'          => '404_image',
					'type'        => 'media',
					'label'       => __( 'Custom illustration', 'lerm' ),
					'description' => __( 'Optional image used instead of the default 404 illustration.', 'lerm' ),
					'group_heading' => __( '404 page', 'lerm' ),
					'default'     => array(),
				),
				array(
					'id'      => '404_show_search',
					'type'    => 'switcher',
					'label'   => __( 'Show search box', 'lerm' ),
					'group_heading' => __( '404 page', 'lerm' ),
					'default' => true,
				),
			),
		),
		array(
			'id'     => 'posts',
			'label'  => __( 'Posts', 'lerm' ),
			'fields' => array(
				array(
					'id'          => 'summary_or_full',
					'type'        => 'radio',
					'label'       => __( 'Archive post display mode', 'lerm' ),
					'description' => __( 'Choose whether archive pages render full post bodies or excerpts.', 'lerm' ),
					'group_heading' => __( 'Archive cards', 'lerm' ),
					'default'     => 'content_summary',
					'choices'     => array(
						'content_full'    => __( 'Full content', 'lerm' ),
						'content_summary' => __( 'Excerpt only', 'lerm' ),
					),
				),
				array(
					'id'          => 'excerpt_length',
					'type'        => 'number',
					'label'       => __( 'Excerpt length (words)', 'lerm' ),
					'description' => __( 'Number of words shown in automatically generated excerpts.', 'lerm' ),
					'group_heading' => __( 'Archive cards', 'lerm' ),
					'default'     => 95,
					'min'         => 0,
					'max'         => 300,
					'step'        => 5,
				),
				array(
					'id'          => 'show_thumbnail',
					'type'        => 'switcher',
					'label'       => __( 'Show archive thumbnails', 'lerm' ),
					'description' => __( 'Displays featured or fallback thumbnails on archive cards.', 'lerm' ),
					'group_heading' => __( 'Archive cards', 'lerm' ),
					'default'     => true,
				),
				array(
					'id'               => 'thumbnail_gallery',
					'type'             => 'gallery',
					'label'            => __( 'Fallback thumbnail pool', 'lerm' ),
					'description'      => __( 'Images used when a post does not have a featured image.', 'lerm' ),
					'group_heading' => __( 'Archive cards', 'lerm' ),
					'default'          => array(),
					'dependency_field' => 'show_thumbnail',
					'dependency_value' => '1',
				),
				array(
					'id'          => 'cat_exclude',
					'type'        => 'checkbox_list',
					'label'       => __( 'Exclude categories', 'lerm' ),
					'description' => __( 'Posts in these categories will not appear on the main blog archive.', 'lerm' ),
					'group_heading' => __( 'Archive cards', 'lerm' ),
					'default'     => array(),
					'choices'     => array( ThemeOptionsDefinition::class, 'category_choices' ),
				),
				array(
					'id'          => 'load_more',
					'type'        => 'switcher',
					'label'       => __( 'Ajax "Load more" pagination', 'lerm' ),
					'description' => __( 'Replaces standard archive pagination with a load-more button.', 'lerm' ),
					'group_heading' => __( 'Archive cards', 'lerm' ),
					'default'     => false,
				),
				array(
					'id'      => 'loading_animate',
					'type'    => 'switcher',
					'label'   => __( 'Archive card entrance animation', 'lerm' ),
					'group_heading' => __( 'Archive cards', 'lerm' ),
					'default' => false,
				),
				array(
					'id'          => 'summary_meta',
					'type'        => 'sorter',
					'label'       => __( 'Archive meta items', 'lerm' ),
					'description' => __( 'Drag to set order, then tick the items that should appear below archive cards.', 'lerm' ),
					'group_heading' => __( 'Archive cards', 'lerm' ),
					'default'     => ThemeOptionsDefinition::summary_meta_default(),
					'choices'     => array( ThemeOptionsDefinition::class, 'post_meta_choices' ),
				),
				array(
					'id'      => 'post_navigation',
					'type'    => 'switcher',
					'label'   => __( 'Previous / next post navigation', 'lerm' ),
					'group_heading' => __( 'Single post', 'lerm' ),
					'default' => true,
				),
				array(
					'id'      => 'disable_pingback',
					'type'    => 'switcher',
					'label'   => __( 'Disable pingbacks', 'lerm' ),
					'group_heading' => __( 'Single post', 'lerm' ),
					'default' => false,
				),
				array(
					'id'          => 'enable_code_highlight',
					'type'        => 'switcher',
					'label'       => __( 'Syntax highlighting', 'lerm' ),
					'description' => __( 'Enable Prism.js highlighting for code blocks inside posts.', 'lerm' ),
					'group_heading' => __( 'Single post', 'lerm' ),
					'default'     => false,
				),
				array(
					'id'          => 'author_bio',
					'type'        => 'switcher',
					'label'       => __( 'Author bio box', 'lerm' ),
					'description' => __( 'Show the author biography card below single posts.', 'lerm' ),
					'group_heading' => __( 'Single post', 'lerm' ),
					'default'     => false,
				),
				array(
					'id'      => 'related_posts',
					'type'    => 'switcher',
					'label'   => __( 'Show related posts', 'lerm' ),
					'group_heading' => __( 'Single post', 'lerm' ),
					'default' => false,
				),
				array(
					'id'               => 'related_number',
					'type'             => 'number',
					'label'            => __( 'Related posts count', 'lerm' ),
					'group_heading' => __( 'Single post', 'lerm' ),
					'default'          => 5,
					'min'              => 1,
					'max'              => 12,
					'step'             => 1,
					'dependency_field' => 'related_posts',
					'dependency_value' => '1',
				),
				array(
					'id'          => 'single_top',
					'type'        => 'sorter',
					'label'       => __( 'Header meta items', 'lerm' ),
					'description' => __( 'Controls the post meta shown above the article body.', 'lerm' ),
					'group_heading' => __( 'Single post meta', 'lerm' ),
					'default'     => ThemeOptionsDefinition::single_top_default(),
					'choices'     => array( ThemeOptionsDefinition::class, 'post_meta_choices' ),
				),
				array(
					'id'          => 'single_bottom',
					'type'        => 'sorter',
					'label'       => __( 'Footer meta items', 'lerm' ),
					'description' => __( 'Controls the post meta shown below the article body.', 'lerm' ),
					'group_heading' => __( 'Single post meta', 'lerm' ),
					'default'     => ThemeOptionsDefinition::single_bottom_default(),
					'choices'     => array( ThemeOptionsDefinition::class, 'post_meta_choices' ),
				),
				array(
					'id'          => 'toc_enable',
					'type'        => 'switcher',
					'label'       => __( 'Enable table of contents', 'lerm' ),
					'description' => __( 'Auto-generate a TOC from H2/H3 headings inside post content.', 'lerm' ),
					'group_heading' => __( 'Table of contents', 'lerm' ),
					'default'     => false,
				),
				array(
					'id'               => 'toc_min_headings',
					'type'             => 'number',
					'label'            => __( 'Minimum headings required', 'lerm' ),
					'description'      => __( 'The TOC stays hidden when a post has fewer headings than this value.', 'lerm' ),
					'group_heading' => __( 'Table of contents', 'lerm' ),
					'default'          => 3,
					'min'              => 1,
					'max'              => 20,
					'step'             => 1,
					'dependency_field' => 'toc_enable',
					'dependency_value' => '1',
				),
				array(
					'id'               => 'toc_position',
					'type'             => 'button_set',
					'label'            => __( 'TOC position', 'lerm' ),
					'group_heading' => __( 'Table of contents', 'lerm' ),
					'default'          => 'before_content',
					'choices'          => array(
						'before_content' => __( 'Above content', 'lerm' ),
						'sidebar'        => __( 'In sidebar', 'lerm' ),
						'floating'       => __( 'Floating panel', 'lerm' ),
					),
					'dependency_field' => 'toc_enable',
					'dependency_value' => '1',
				),
				array(
					'id'               => 'toc_collapsed',
					'type'             => 'switcher',
					'label'            => __( 'Collapse TOC by default', 'lerm' ),
					'group_heading' => __( 'Table of contents', 'lerm' ),
					'default'          => false,
					'dependency_field' => 'toc_enable',
					'dependency_value' => '1',
				),
				array(
					'id'      => 'post_likes_enable',
					'type'    => 'switcher',
					'label'   => __( 'Show post like button', 'lerm' ),
					'group_heading' => __( 'Engagement', 'lerm' ),
					'default' => true,
				),
				array(
					'id'      => 'comment_likes_enable',
					'type'    => 'switcher',
					'label'   => __( 'Show comment like button', 'lerm' ),
					'group_heading' => __( 'Engagement', 'lerm' ),
					'default' => true,
				),
				array(
					'id'      => 'post_views_enable',
					'type'    => 'switcher',
					'label'   => __( 'Show post view count', 'lerm' ),
					'group_heading' => __( 'Engagement', 'lerm' ),
					'default' => true,
				),
				array(
					'id'               => 'views_unique_only',
					'type'             => 'switcher',
					'label'            => __( 'Count unique visitors only', 'lerm' ),
					'description'      => __( 'Avoids inflating view counts with repeated reloads from the same browser session.', 'lerm' ),
					'group_heading' => __( 'Engagement', 'lerm' ),
					'default'          => true,
					'dependency_field' => 'post_views_enable',
					'dependency_value' => '1',
				),
				array(
					'id'      => 'share_position',
					'type'    => 'button_set',
					'label'   => __( 'Share button position', 'lerm' ),
					'group_heading' => __( 'Sharing & copyright', 'lerm' ),
					'default' => 'bottom',
					'choices' => array(
						'top'    => __( 'Above content', 'lerm' ),
						'bottom' => __( 'Below content', 'lerm' ),
						'both'   => __( 'Both', 'lerm' ),
						'none'   => __( 'Hidden', 'lerm' ),
					),
				),
				array(
					'id'      => 'share_show_count',
					'type'    => 'switcher',
					'label'   => __( 'Show share count', 'lerm' ),
					'group_heading' => __( 'Sharing & copyright', 'lerm' ),
					'default' => false,
				),
				array(
					'id'          => 'post_copyright_enable',
					'type'        => 'switcher',
					'label'       => __( 'Show copyright / repost notice', 'lerm' ),
					'description' => __( 'Displays a copyright reminder and permalink block beneath single posts.', 'lerm' ),
					'group_heading' => __( 'Sharing & copyright', 'lerm' ),
					'default'     => true,
				),
				array(
					'id'               => 'post_copyright_text',
					'type'             => 'textarea',
					'label'            => __( 'Custom copyright text', 'lerm' ),
					'description'      => __( 'Overrides the default copyright message. Leave empty to use the theme default.', 'lerm' ),
					'group_heading' => __( 'Sharing & copyright', 'lerm' ),
					'default'          => '',
					'rows'             => 4,
					'placeholder'      => __( 'This article was published by ... Please credit the original source when reposting.', 'lerm' ),
					'dependency_field' => 'post_copyright_enable',
					'dependency_value' => '1',
				),
			),
		),
		array(
			'id'     => 'sidebars',
			'label'  => __( 'Sidebars', 'lerm' ),
			'fields' => array(
				// Switching to a more flexible group field for sidebar management
				// since the old static select fields were getting unwieldy.
				array(
					'id'          => 'register_sidebars',
					'type'        => 'group',
					'label'       => __( 'Custom sidebars', 'lerm' ),
					'description' => __( 'Additional sidebars registered by the theme. Save once before assigning them elsewhere.', 'lerm' ),
					'group_heading' => __( 'Custom sidebars', 'lerm' ),
					'default'     => array(),
					'button_text' => __( 'Add sidebar', 'lerm' ),
					'fields'      => array(
						array(
							'id'          => 'sidebar_title',
							'type'        => 'text',
							'label'       => __( 'Sidebar name', 'lerm' ),
							'description' => __( 'Human-friendly name shown in Widgets and Customizer panels.', 'lerm' ),
							'default'     => '',
							'placeholder' => __( 'Example: Article sidebar', 'lerm' ),
						),
					),
				),
				array(
					'id'          => 'single_sidebar_select',
					'type'        => 'select',
					'label'       => __( 'Single post sidebar', 'lerm' ),
					'description' => __( 'Sidebar used on single post pages.', 'lerm' ),
					'group_heading' => __( 'Sidebar assignments', 'lerm' ),
					'default'     => 'home-sidebar',
					'choices'     => array( ThemeOptionsDefinition::class, 'sidebar_choices' ),
				),
				array(
					'id'          => 'blog_sidebar_select',
					'type'        => 'select',
					'label'       => __( 'Blog archive sidebar', 'lerm' ),
					'description' => __( 'Sidebar used on blog archives and home loops.', 'lerm' ),
					'group_heading' => __( 'Sidebar assignments', 'lerm' ),
					'default'     => 'home-sidebar',
					'choices'     => array( ThemeOptionsDefinition::class, 'sidebar_choices' ),
				),
				array(
					'id'          => 'front_page_sidebar',
					'type'        => 'select',
					'label'       => __( 'Front page sidebar', 'lerm' ),
					'description' => __( 'Sidebar used on the static front page template.', 'lerm' ),
					'group_heading' => __( 'Sidebar assignments', 'lerm' ),
					'default'     => 'home-sidebar',
					'choices'     => array( ThemeOptionsDefinition::class, 'sidebar_choices' ),
				),
				array(
					'id'          => 'page_sidebar',
					'type'        => 'select',
					'label'       => __( 'Static page sidebar', 'lerm' ),
					'description' => __( 'Sidebar used on standard WordPress pages.', 'lerm' ),
					'group_heading' => __( 'Sidebar assignments', 'lerm' ),
					'default'     => 'home-sidebar',
					'choices'     => array( ThemeOptionsDefinition::class, 'sidebar_choices' ),
				),
				array(
					'id'          => 'comment_excerpt_length',
					'type'        => 'number',
					'label'       => __( 'Latest comments excerpt length', 'lerm' ),
					'description' => __( 'Controls excerpt length inside the latest comments widget.', 'lerm' ),
					'group_heading' => __( 'Widget settings', 'lerm' ),
					'default'     => 95,
					'min'         => 0,
					'max'         => 300,
					'step'        => 5,
				),
			),
		),
	),
);
